### ISSUE TITLE
Recent code comments

### ISSUE THREAD

**Issue by suntong** [eatMoreApple/openwechat#10]
Hi @eatMoreApple, 

Did you get a change to review my recent code comments as the followings:

- https://github.com/eatMoreApple/openwechat/commit/258ac4f2363e0c0f4f8cb26fb569b6f4813aa0de#commitcomment-50150196
- https://github.com/eatMoreApple/openwechat/commit/3c7fec07f360cb1b1cabff3bf59900c4bcc8a169#commitcomment-50192943
- https://github.com/eatMoreApple/openwechat/commit/5ff43c4ceab035d1262e8fc32f0970ada0d858d6#commitcomment-50193630 

thx

**Comment by suntong** [comment]
![image](https://user-images.githubusercontent.com/422244/117904988-6392ab00-b2a0-11eb-831e-96d464616d4c.png)

@eatMoreApple is it possible that you filter your code through `gofmt` before you do commits?
Many tools provide such feature out of the box, and I believe `goland` should be able to do that for each save as well. 

Please fix it. the screenshot above are not real changes, and should not switch back and forth each time when doing commits. 

Thanks

**Comment by eatMoreApple** [comment]
很抱歉..这方面的工具我也使用过了，但是不起作用，不知道是不是我两台不同操作系统的电脑相互提交所造成现象，但是不应该啊...

**Comment by suntong** [comment]
Oh, I thought you were using two machines, thanks for the explanation, now I know it's 两台不同操作系统.

I might be able to help, let me ask you first, 

Have you tried to use [goimports](golang.org/x/tools/cmd/goimports) to filter your code for each save?
Were it able to add the missing `import` automatically for you?

**Comment by eatMoreApple** [comment]
goland可以自动导入使用的包，但是我没有使用过`goimports`，只是简单的利用了下goland的的代码格式化的快捷键`ctrl + alt + l`

**Comment by suntong** [comment]
Oh, in that case, might your goland的的代码格式化 setting be different between your two machines? 
Looks like their indent level are set differently. Have you checked that yet?

**Comment by eatMoreApple** [comment]
这个问题貌似没有出现过了，感谢您的帮助！
