### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by wolfboygg** [eatmoreapple/openwechat#100]
![image](https://user-images.githubusercontent.com/41662005/152949230-fc4d3999-66f2-4f3b-a141-0d982cd209fb.png)

**Comment by wangle201210** [comment]
同上

**Comment by idolUD** [comment]
微信号不支持网页登陆，换桌面模式

**Comment by wangle201210** [comment]
> 微信号不支持网页登陆，换桌面模式
桌面模式也会报错：
301 response missing Location header

**Comment by eatmoreapple** [comment]
登录出错的都是登录不上网页版的，能够登录网页版的微信的用户才能使用本项目

**Comment by hgmmym** [comment]
同上
网页版登录：XML syntax error on line 8: invalid UTF-8

**Comment by eatmoreapple** [comment]
v1.1.11版本已恢复Desktop模式的正常使用。

**Comment by jinfagang** [comment]
@eatmoreapple 这个原理是啥，怎么突破的网页限制啊，又有什么局限呢

**Comment by eatmoreapple** [comment]
@jinfagang uos微信开放了参数，登录时候把那个参数加上就能登录网页版微信了，功能和网页版微信一样。
