### ISSUE TITLE
XML syntax error on line 8: invalid UTF-8

### ISSUE THREAD

**Issue by captainstdin** [eatmoreapple/openwechat#104]
2022/08/22 14:18:55 扫码成功,请在手机上确认登录
2022/08/22 14:19:04 登录成功
XML syntax error on line 8: invalid UTF-8

OS win2012
Golang 1.18
platform x86_64

**Comment by eatmoreapple** [comment]
用DeskTop模式登录试试

**Comment by captainstdin** [comment]
桌面模式好用，

**Comment by eatmoreapple** [comment]
OK
