### ISSUE TITLE
windows错误

### ISSUE THREAD

**Issue by jinfagang** [eatmoreapple/openwechat#105]
![image](https://user-images.githubusercontent.com/21303438/189487561-65f93340-0189-4871-b012-e421c63be7f3.png)

windows上编码错误咋回事

**Comment by jinfagang** [comment]
切换到桌面版可以，大神可以解答两个疑问吗？
1. 这个桌面版是怎么实现的？用多了是不是容易i导致封号？
2. 为什么用网页版有上面那个错误？似乎也提示登录成功了。

**Comment by eatmoreapple** [comment]
您好，tx在linux发行版uos上面发布了一个微信，其实就是electron套的网页版微信，并且开放了一个参数使得网页版登陆不了的用户都能登陆了。
目前没有封号反馈。您在使用您的机器人的时候尽量控制发送消息的频率，不要被风控到就好了。
