### ISSUE TITLE
如何catch panic error

### ISSUE THREAD

**Issue by lucasjinreal** [eatmoreapple/openwechat#106]
目前似乎在运行过程中，偶尔会发生panic error，尚不知道为何原因产生，有什么办法可以catch这个panic，一旦发生就pass，继续运行啊

**Comment by eatmoreapple** [comment]
panic是默认行为，重载这个默认行为即可。
需要对Bot的MessageErrorHandler重新赋值。

JinTian ***@***.***> 于2022年9月13日周二 14:40写道：

**Comment by eatmoreapple** [comment]
能追踪到是哪行代码吗？

**Comment by jinfagang** [comment]
<img width="872" alt="image" src="https://user-images.githubusercontent.com/21303438/189889509-6a41765f-3f5e-473a-ad11-500765d13855.png">

zh这是log，大佬请分析一下

**Comment by jinfagang** [comment]
会是我这行代码造成的吗？
<img width="648" alt="image" src="https://user-images.githubusercontent.com/21303438/189889684-5bea824d-a331-45c3-94cc-c31da6155f66.png">

**Comment by eatmoreapple** [comment]
没有处理err，看看error

**Comment by xiaotuzididi** [comment]
thankyou good
