### ISSUE TITLE
功能请求：是否可以增加常用设备

### ISSUE THREAD

**Issue by YXH-YXH** [eatmoreapple/openwechat#111]
微信（常用）PC端可以（不用手机扫码）一键登录

这个功能是否有考虑实现？
   实现这个功能大概需要什么前提条件？

另：
你这个项目非常棒

**Comment by eatmoreapple** [comment]
谢谢。用热登录只需要扫码登录一次即可，下次登录不需要重复扫码。

**Comment by eatmoreapple** [comment]
除了热登录之外还有一种直接发消息给手机端确认登录，那是很早之前实现过一次，现在好久没搞了。
