### ISSUE TITLE
[bug:fix] func (m *Message) Receiver() (*User, error) 忽略了 文件传输助手 的情况

### ISSUE THREAD

**Issue by YXH-YXH** [eatmoreapple/openwechat#113]
复现思路：
```go
// Bot.MessageHandler=
MessageHandler(msg *openwechat.Message) {
        receiver, err = msg.Receiver()
        if err != nil {
                log.Print(err)
        }
}
```
1.必现：接收方为 文件传输助手
2.偶现：
在messageType=51的情况下 或 特定群聊消息（少于10人的群聊）

我自行更改了一下内容，解决了必现的问题（未充分测试，可能存在未考虑到的情况）
（注意红框部分）

<img width="477" alt="Receiver" src="https://user-images.githubusercontent.com/35206235/192144126-14d4a645-b9a2-454b-a2ec-3270e9b565b0.png">

**Comment by xiaotuzididi** [comment]
thanks

**Comment by eatmoreapple** [comment]
已修复
