### ISSUE TITLE
是否能增加对公众号的深入功能？

### ISSUE THREAD

**Issue by 445022889** [eatmoreapple/openwechat#114]
比如说公众号文章的抓取？

**Comment by eatmoreapple** [comment]
暂时没有这个想法

**Comment by dev-techmoe** [comment]
请问这个sdk目前是否有能力接收到公众号的推送？  
至于怎么处理内容无所谓，这个库也无需去做，只要能接收到推送，拿到文章URL就可以了。  
之前很多人一直在寻找一个完美的微信公众号rss订阅方案，如果这个sdk能拿到文章推送的话，我觉得对于这个需求来说会是一个比较大的突破。
