### ISSUE TITLE
self.Friends() 获取的好友不全

### ISSUE THREAD

**Issue by drharryhe** [eatmoreapple/openwechat#116]
self.Friends() 获取的好友不全

您好，测试微信上有1000多个好友，但是每次调用Friends都只获得500多个，而且search明显存在且最近联系的好友，也返回null，请问是什么原因呢？如何才能获得全部好友。
谢谢您！

**Comment by seosite** [comment]
感谢开源，我也有同样的问题，获取到的好友、群聊和公众号，都只会显示一部分。

**Comment by drharryhe** [comment]
> 感谢开源，我也有同样的问题，获取到的好友、群聊和公众号，都只会显示一部分。

问题找到了，WebWxGetContact的实现有问题。我fork了一个分支修复这个bug， 可以移步 github.com/drharryhe/openwechat看看

**Comment by eatmoreapple** [comment]
> > 感谢开源，我也有同样的问题，获取到的好友、群聊和公众号，都只会显示一部分。
> 
> 问题找到了，WebWxGetContact的实现有问题。我fork了一个分支修复这个bug， 可以移步 github.com/drharryhe/openwechat看看

大哥牛逼

**Comment by drharryhe** [comment]
fork to  github.com/drharryhe/openwechat and  fixed

**Comment by eatmoreapple** [comment]
已解决
