### ISSUE TITLE
More insight into the login handshaking

### ISSUE THREAD

**Issue by suntong** [eatMoreApple/openwechat#12]
Following up on #11,

Please add a debug option so that people can completely trace the login handshaking steps, logging to console what request is being sending over, and what the response and its headers are as well. 

Thus when people experience problem similar to #11, by sending the detailed login handshaking trace, we can have a pretty good understanding of what's going on, and might be able to pinpoint the problem right away. 

Pls consider. thx

**Comment by eatMoreApple** [comment]
```
package main

import (
	"fmt"
	"github.com/eatMoreApple/openwechat"
	"net/http"
)

type ResponseHooker struct{}

func (r ResponseHooker) BeforeRequest(req *http.Request) {}

func (r ResponseHooker) AfterRequest(response *http.Response, err error) {
	fmt.Println(response.Request.URL.Path)
	fmt.Println(response.Request.Header)
}

func main() {
	bot := openwechat.DefaultBot(openwechat.Desktop)
	bot.Caller.Client.AddHttpHook(ResponseHooker{})
}
```

目前您可以配合一些实用的日志库来实现类似的功能

**Comment by suntong** [comment]
Yep, that'll do. thx. I'll try today...

**Comment by suntong** [comment]
I tried it, but got:

```
bot.Caller.Client.AddHttpHook undefined (type *openwechat.Client has no field or method AddHttpHook)
```

**Comment by suntong** [comment]
> 目前您可以配合一些实用的日志库来实现类似的功能

Oh, I thought I should implement my own `AfterRequest()` function.  
Or did you mean I should implement `bot.Caller.Client.AddHttpHook` instead?

**Comment by suntong** [comment]
> I thought I should implement my own `AfterRequest()` function.

Problem still not solved. 

Can you reopen pls?
