### ISSUE TITLE
XML syntax error on line 8: invalid UTF-8

### ISSUE THREAD

**Issue by eatmoreapple** [eatmoreapple/openwechat#128]
使用`desktop`模式

`bot := openwechat.DefaultBot(openwechat.Desktop)`

**Comment by MiiW** [comment]
> 使用`desktop`模式
> 
> `bot := openwechat.DefaultBot(openwechat.Desktop)`

看过源码，感觉可以校验一下是否满足登陆后成功的条件，unmarshal的时候。失败直接报错，先打印“登陆成功”之后再报错不太友好

**Comment by eatmoreapple** [comment]
> > 使用`desktop`模式
> > `bot := openwechat.DefaultBot(openwechat.Desktop)`
> 
> 看过源码，感觉可以校验一下是否满足登陆后成功的格式，unmarshal的时候。失败直接报错，先打印“登陆成功”之后再报错不太友好

嗯，这个顺序修复了，这个xml语法错误也不会再出现了。

**Comment by eatmoreapple** [comment]
@MiiW 嗯，这个顺序修复了，这个xml语法错误也不会再出现了。
