### ISSUE TITLE
是否存在可以唯一确定一个联系人的标识

### ISSUE THREAD

**Issue by Hyffer** [eatmoreapple/openwechat#130]
> UserName是当前会话唯一的身份标识，且仅作用于当前会话。下次登录该属性值则会被改变。

我所了解的比如wxid，虽然可变，但一年只可以修改一次。请问是否有持久性的唯一标识，可以永久标识一个对象？可否添加一下支持？

谢谢这么棒的项目！

**Comment by eatmoreapple** [comment]
您好，新版本已经支持获取唯一身份标识符的获取。

**Comment by Hyffer** [comment]
好的，感谢！
