### ISSUE TITLE
write storage.json: bad file descriptor

### ISSUE THREAD

**Issue by 869413421** [eatmoreapple/openwechat#138]
热登录登录失败 提示 write storage.json: bad file descriptor

**Comment by eatmoreapple** [comment]
是否存在多进程或者多个协程尝试打开同一份文件的场景？

**Comment by 869413421** [comment]
> 是否存在多进程或者多个协程尝试打开同一份文件的场景？

我同时使用热登陆和普通登陆导致的。

**Comment by wuhao1477** [comment]
> > 是否存在多进程或者多个协程尝试打开同一份文件的场景？
> 
> 我同时使用热登陆和普通登陆导致的。

我这边是每次登录都要扫码

**Comment by freejacklee** [comment]
@wuhao1477 storage.json位置在哪里？
