### ISSUE TITLE
是否有好方法根据user对象得到一个friend对象？

### ISSUE THREAD

**Issue by li1553770945** [eatmoreapple/openwechat#141]
我的需求是：有人给我发消息，我就把他拉进一个群。
msg.Sender()返回的是一个User对象，AddFriendsIntoGroup()需要的是friend对象。除了遍历所有好友列表找到sender是哪个好友，是否有更好的方法？

**Comment by eatmoreapple** [comment]
因为sender有时候是friend，有时候是group，为了通用性，就返回user。通过user.IsFriend 或者 user.IsGroup 来判断是否为 好友或者群组，最后直接构造一个 &Friend{User: sender}

**Comment by li1553770945** [comment]
好的，明白了，感谢！
