### ISSUE TITLE
是否可以自定义网络重试次数？

### ISSUE THREAD

**Issue by li1553770945** [eatmoreapple/openwechat#149]
平台：Windows10
Go版本：go1.19.4 windows/amd64
微信号是两周前注册的
表现：登陆成功后，过一分钟左右发消息，bot就不能用了。

通过调试跟踪，发现是caller.go的`func (c *Client) SyncCheck(request *BaseRequest, info *LoginInfo, response *WebInitResponse) (*http.Response, error)`返回了一个err，再继续追踪下去是client.go的`func (c *Client) do(req *http.Request) (*http.Response, error)`抛出的错误。错误信息为：`wechat network error: Get "https://webpush.wx2.qq.com/cgi-bin/mmwebwx-bin/synccheck?xxxx": net/http: HTTP/1.x transport connection broken: malformed HTTP status code "0"`。
我强行把client中的第74行，`maxRetry`这个变量从2改成了10，就会好很多了，基本上不掉了。但是强行改库总不是一个可行的方式，是否可以加一个接口，自定义网络错误的重试次数？
![image](https://user-images.githubusercontent.com/55867654/206866736-1cb7180e-824a-4329-a543-de5fe6454a2d.png)

**Comment by eatmoreapple** [comment]
可以的

**Comment by eatmoreapple** [comment]
已支持

**Comment by li1553770945** [comment]
好的，感谢！

**Comment by bravelionet** [comment]
@li1553770945  您好,请问您是怎么解决的呢, 官方说明已经支持, 怎么修改这个值呢

**Comment by eatmoreapple** [comment]
> 

`bot := openwechat.DefaultBot(openwechat.Desktop)
	bot.Caller.Client.MaxRetryTimes = 10`
