### ISSUE TITLE
IsJoinGroup 扫码进群的提示不了。 扫码进群的提示文案，少了一个了。

### ISSUE THREAD

**Issue by yuhaibo19891112** [eatmoreapple/openwechat#156]
// IsJoinGroup 判断是否有人加入了群聊
func (m *Message) IsJoinGroup() bool {
	return m.IsSystem() && strings.Contains(m.Content, "加入了群聊") && m.IsSendByGroup()
}

-->return m.IsSystem() &&(strings.Contains(m.Content, "加入了群聊") || strings.Contains(m.Content, "加入群聊")) && m.IsSendByGroup()

**Comment by eatmoreapple** [comment]
这个会误判的

**Comment by xiaotuzididi** [comment]
good thankyou

**Comment by eatmoreapple** [comment]
已经修复了
