### ISSUE TITLE
User信息能否添加用户的wxid?是无法获取吗?

### ISSUE THREAD

**Issue by zack-sys** [eatmoreapple/openwechat#157]
用户wxid是唯一标识,发送给好友信息也可以通过wxid发送这样的操作. 收到消息最好也能有 发送方和接收方的wxid

**Comment by zack-sys** [comment]
看获取所有联系人的响应来看,是没有wxid的,可否有其他方式可以获取到呢?

**Comment by lixh00** [comment]
web协议不含有wxid字段

**Comment by eatmoreapple** [comment]
有个ID方法可以获取唯一标识
