### ISSUE TITLE
这个可以自动加好友吗

### ISSUE THREAD

**Issue by qingweiSun** [eatmoreapple/openwechat#158]

**Comment by eatmoreapple** [comment]
不可以的，可以同意好友请求

**Comment by qingweiSun** [comment]
好的，谢谢

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 多吃点苹果 ***@***.***>
发送时间: Monday, December 12, 2022 5:33:31 PM
收件人: eatmoreapple/openwechat ***@***.***>
抄送: 别叫我天真 ***@***.***>; Author ***@***.***>
主题: Re: [eatmoreapple/openwechat] 这个可以自动加好友吗 (Issue #158)


不可以的，可以同意好友请求

―
