### ISSUE TITLE
关于微信登录问题

### ISSUE THREAD

**Issue by fristfun** [eatMoreApple/openwechat#16]
扫描二维码提示：
为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>
请问该如何避开这个问题呢

**Comment by eatMoreApple** [comment]
你试一下`Desktop`模式
