### ISSUE TITLE
program not response to wechat msg with log: RetCode:0  Selector:7

### ISSUE THREAD

**Issue by Stars17** [eatmoreapple/openwechat#160]
rapid RetCode:0  Selector:7, about 5 times per second.
and program not response to wechat msg, I must restart it manually.

2022/12/12 17:31:15 RetCode:0  Selector:7
2022/12/12 17:31:15 RetCode:0  Selector:7
2022/12/12 17:31:15 RetCode:0  Selector:7
2022/12/12 17:31:15 RetCode:0  Selector:7
2022/12/12 17:31:16 RetCode:0  Selector:7
2022/12/12 17:31:16 RetCode:0  Selector:7
2022/12/12 17:31:16 RetCode:0  Selector:7
2022/12/12 17:31:16 RetCode:0  Selector:7
2022/12/12 17:31:16 RetCode:0  Selector:7
2022/12/12 17:31:17 RetCode:0  Selector:7
2022/12/12 17:31:17 RetCode:0  Selector:7
2022/12/12 17:31:17 RetCode:0  Selector:7
2022/12/12 17:31:17 RetCode:0  Selector:7
2022/12/12 17:31:17 RetCode:0  Selector:7
2022/12/12 17:31:18 RetCode:0  Selector:7
2022/12/12 17:31:18 RetCode:0  Selector:7
2022/12/12 17:31:18 RetCode:0  Selector:7
2022/12/12 17:31:18 RetCode:0  Selector:7
2022/12/12 17:31:18 RetCode:0  Selector:7
2022/12/12 17:31:19 RetCode:0  Selector:7
2022/12/12 17:31:19 RetCode:0  Selector:7
2022/12/12 17:31:19 RetCode:0  Selector:7
2022/12/12 17:31:19 RetCode:0  Selector:7
2022/12/12 17:31:19 RetCode:0  Selector:7
2022/12/12 17:31:20 RetCode:0  Selector:7
2022/12/12 17:31:20 RetCode:0  Selector:7
2022/12/12 17:31:20 RetCode:0  Selector:7
2022/12/12 17:31:20 RetCode:0  Selector:7
2022/12/12 17:31:20 RetCode:0  Selector:7
2022/12/12 17:31:21 RetCode:0  Selector:7
2022/12/12 17:31:21 RetCode:0  Selector:7
2022/12/12 17:31:21 RetCode:0  Selector:7
2022/12/12 17:31:21 RetCode:0  Selector:7
2022/12/12 17:31:21 RetCode:0  Selector:7
2022/12/12 17:31:21 RetCode:0  Selector:7
2022/12/12 17:31:22 RetCode:0  Selector:7
2022/12/12 17:31:22 RetCode:0  Selector:7
2022/12/12 17:31:22 RetCode:0  Selector:7
2022/12/12 17:31:22 RetCode:0  Selector:7
2022/12/12 17:31:22 RetCode:0  Selector:7
2022/12/12 17:31:23 RetCode:0  Selector:7
2022/12/12 17:31:23 RetCode:0  Selector:7
2022/12/12 17:31:23 RetCode:0  Selector:7
2022/12/12 17:31:23 RetCode:0  Selector:7
2022/12/12 17:31:23 RetCode:0  Selector:7
2022/12/12 17:31:24 RetCode:0  Selector:7
2022/12/12 17:31:24 RetCode:0  Selector:7
2022/12/12 17:31:24 RetCode:0  Selector:7
2022/12/12 17:31:24 RetCode:0  Selector:7
2022/12/12 17:31:24 RetCode:0  Selector:7
2022/12/12 17:31:25 RetCode:0  Selector:7
2022/12/12 17:31:25 RetCode:0  Selector:7
2022/12/12 17:31:25 RetCode:0  Selector:7
2022/12/12 17:31:25 RetCode:0  Selector:7
2022/12/12 17:31:25 RetCode:0  Selector:7
2022/12/12 17:31:26 RetCode:0  Selector:7
2022/12/12 17:31:26 RetCode:0  Selector:7
2022/12/12 17:31:26 RetCode:0  Selector:7
2022/12/12 17:31:26 RetCode:0  Selector:7
2022/12/12 17:31:26 RetCode:0  Selector:7
2022/12/12 17:31:27 RetCode:0  Selector:7
2022/12/12 17:31:27 RetCode:0  Selector:7
2022/12/12 17:31:27 RetCode:0  Selector:7
2022/12/12 17:31:27 RetCode:0  Selector:7
2022/12/12 17:31:27 RetCode:0  Selector:7
2022/12/12 17:31:28 RetCode:0  Selector:7
2022/12/12 17:31:28 RetCode:0  Selector:7
2022/12/12 17:31:28 RetCode:0  Selector:7
2022/12/12 17:31:28 RetCode:0  Selector:7
2022/12/12 17:31:28 RetCode:0  Selector:7
2022/12/12 17:31:28 RetCode:0  Selector:7
2022/12/12 17:31:29 RetCode:0  Selector:7
2022/12/12 17:31:29 RetCode:0  Selector:7

**Comment by eatmoreapple** [comment]
你是不是发文件了？
发送文件之后持续一段时间这样

**Comment by Stars17** [comment]
Do stickers and pictures belong to files? Actually, I just send texts, stickers, and photos.

**Comment by eatmoreapple** [comment]
图片也属于文件的，图片要上传到微信的服务器，上传之后就会持续一段时间这样，属于正常现象。
