### ISSUE TITLE
Reply Text没问题, 但ReplyImage和ReplyFile报EOF

### ISSUE THREAD

**Issue by kokocooler2020** [eatmoreapple/openwechat#177]
Reply Text没问题, 但ReplyImage和ReplyFile报EOF

**Comment by eatmoreapple** [comment]
是空文件吗？

**Comment by kokocooler2020** [comment]
不是空文件, ReplyImage()一个512x512的图片, 会返回EOF, 但对方可以收到图片.

**Comment by kokocooler2020** [comment]
不是空文件, 是在同一个方法内, 先下载一个文件, 再将这个文件的file变量传给ReplyImage()就会报EOF.
但如果重新打开这个文件, 将新文件的变量传给ReplyImage()就可以正常发送.

**Comment by eatmoreapple** [comment]
现在直接支持传io.Reader了
