### ISSUE TITLE
是否能实现 微信内部扫一扫的oauth2 二次登陆

### ISSUE THREAD

**Issue by captainstdin** [eatmoreapple/openwechat#187]
例如 https://open.weixin.qq.com/connect/oauth2/authorize?appid={$APPID}&redirect_uri={$REDIRECT_URI}&response_type=code&scope=SCOPE&state=STATE#wechat_redirect

**Comment by eatmoreapple** [comment]
不能

**Comment by captainstdin** [comment]
> 不能

**Comment by eatmoreapple** [comment]
不好意思哦
