### ISSUE TITLE
增加一个二维码在终端显示的功能怎么样

### ISSUE THREAD

**Issue by tgNotHouse** [eatmoreapple/openwechat#193]
因为每次展示二维码的时候都去浏览器打开，所以可以在回调那里加一个终端打印的功能，直接把二维码打印到控制台上。

**Comment by eatmoreapple** [comment]
文档里面有一个示例，你可以用那个示例来实现二维码打印到控制的功能。

**Comment by tgNotHouse** [comment]
ok，需要引用个库没问题吗
