### ISSUE TITLE
New openwechat org?

### ISSUE THREAD

**Issue by suntong** [eatMoreApple/openwechat#20]
Following up on #12, which I'm planning to put your suggestions into real code/project, 

What would you say that we create a new openwechat GH organization, put `openwechat` under it, and collect all different sample/demo projects there as well? 

So the next person who comes along, can just pick and choose which sample/demo projects to start with, or know which demo projects to turn to troubleshoot (without the need to hunt for it), like having more insight into the login handshaking. 

Comments?

**Comment by eatMoreApple** [comment]
Thank you for your attention on this project and i will implement your suggestions  as soon as i can.

**Comment by suntong** [comment]
have you moved it? I saw that you attempted to, but ...

**Comment by suntong** [comment]
?
