### ISSUE TITLE
【bug】群组group 获取不全

### ISSUE THREAD

**Issue by wenyoufu** [eatmoreapple/openwechat#225]

**Comment by wenyoufu** [comment]
func (s *Self) Groups(update ...bool) (Groups, error) 请修改接口实现

**Comment by eatmoreapple** [comment]
群只能获取保存在通讯录里面的

**Comment by wenyoufu** [comment]
> 群只能获取保存在通讯录里面的

ok，这个issue 先挂这吧，我们看后续有没有更好地解决方案
