### ISSUE TITLE
【opt】获取用户friends接口，建议优先remarkname, 为空再使用nickname

### ISSUE THREAD

**Issue by wenyoufu** [eatmoreapple/openwechat#226]
// implement fmt.Stringer
func (f *Friend) String() string {
	var ret string
	if f.RemarkName == "" {
		ret = fmt.Sprintf("<Friend:%s>", f.NickName)
	} else {
		ret = fmt.Sprintf("<Friend:%s>", f.RemarkName)
	}
	return ret
}

**Comment by eatmoreapple** [comment]
可

**Comment by eatmoreapple** [comment]
已采用建议
