### ISSUE TITLE
【bug】请确认group 群组remarkname 接口的有效性-SearchByRemarkName

### ISSUE THREAD

**Issue by wenyoufu** [eatmoreapple/openwechat#229]

**Comment by eatmoreapple** [comment]
谢谢大哥，group 不开放 remarkname 给用户，所以这个字段目前永远为空

**Comment by wenyoufu** [comment]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/19179965/216761109-1851f733-370c-468f-a0da-2892171f1b5a.png">
该commit fbfd691cb49ec75c369f89bced4607e95f4c37a9 将这段冗余代码去掉吧；就close 这个issue吧

**Comment by eatmoreapple** [comment]
> <img alt="image" width="671" src="https://user-images.githubusercontent.com/19179965/216761109-1851f733-370c-468f-a0da-2892171f1b5a.png">
> 
> 该commit [fbfd691](https://github.com/eatmoreapple/openwechat/commit/fbfd691cb49ec75c369f89bced4607e95f4c37a9) 将这段冗余代码去掉吧；就close 这个issue吧

您说得是这个String有啥用吗?

**Comment by wenyoufu** [comment]
> > <img alt="image" width="671" src="https://user-images.githubusercontent.com/19179965/216761109-1851f733-370c-468f-a0da-2892171f1b5a.png">
> > 该commit [fbfd691](https://github.com/eatmoreapple/openwechat/commit/fbfd691cb49ec75c369f89bced4607e95f4c37a9) 将这段冗余代码去掉吧；就close 这个issue吧
> 
> 您说得是这个String有啥用吗?
g.RemarkName 的判断逻辑没有意义；代码还原成这样；
// implement fmt.Stringer
func (g *Group) String() string {
	return fmt.Sprintf("<Group:%s>", g.NickName)
}
