### ISSUE TITLE
demo桌面模式测试获取friends和groups都是nil

### ISSUE THREAD

**Issue by PittYao** [eatmoreapple/openwechat#238]
![image](https://user-images.githubusercontent.com/26101917/216799071-87f035c6-7a73-48d1-9fa4-68430625616d.png)

![image](https://user-images.githubusercontent.com/26101917/216799058-f98f780c-a19d-4456-b6b0-ea01f27a9a3b.png)

**Comment by eatmoreapple** [comment]
你要用README里面的方式来获取

**Comment by PittYao** [comment]
> 你要用README里面的方式来获取

![image](https://user-images.githubusercontent.com/26101917/216799831-147f1383-7cb9-4279-9e99-05471bc9f66b.png)

**Comment by eatmoreapple** [comment]
请问用是Desktop mode 吗？

**Comment by PittYao** [comment]
> 请问用是Desktop mode 吗？

大概流程是：
直接用的README的代码来跑
openwechat.DefaultBot() 登录报了的login forbidden 用桌面模式登录
换了桌面模式 openwechat.DefaultBot(openwechat.Desktop) 可以登录但是没有friends和group的信息

**Comment by eatmoreapple** [comment]
你别去调试，那些是缓存，第一次肯定是空的，直接看控制台打印的有没有。

**Comment by eatmoreapple** [comment]
如果你好友多要等待一会儿

**Comment by PittYao** [comment]
> 如果你好友多要等待一会儿

我有410个好友,12点开始运行到现在12点13，要多久，之前有人遇到这个情况吗，我看到的是没有数据

**Comment by eatmoreapple** [comment]
没有人反馈过这个情况

**Comment by PittYao** [comment]
> 没有人反馈过这个情况

ok
