### ISSUE TITLE
the socket is not connected

### ISSUE THREAD

**Issue by AncestorDragon** [eatMoreApple/openwechat#24]
访问下面网址扫描二维码登录
https://login.weixin.qq.com/qrcode/oeS-atTcCQ==
Get "https://wx2.qq.com/cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=A6vgjp-VkZyiDwOGBsc__31Y@qrticket_0&uuid=oeS-atTcCQ==&lang=zh_CN&scan=1624880429": dial tcp 61.241.49.55:443: setsockopt: A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.

statusScanned(201)   error

**Comment by eatMoreApple** [comment]
请问你是否使用了代理或者不是用国内的网络的访问的

**Comment by AncestorDragon** [comment]
> 请问你是否使用了代理或者不是用国内的网络的访问的

我想应该 也是不能网页登录的原因，改用desktop也是一样的(这模式没什么区别啊，还是扫码)

**Comment by eatMoreApple** [comment]
两种模式有区别的，如果你还是登录不上，看看你的微信号是不是刚申请不久的。
