### ISSUE TITLE
msg.senderInGroupUserName undefined (type *openwechat.Message has no field or method senderInGroupUserName)

### ISSUE THREAD

**Issue by h3clikejava** [eatmoreapple/openwechat#249]
为啥找不到senderInGroupUserName？ 
用的 github.com/eatmoreapple/openwechat v1.3.9

**Comment by eatmoreapple** [comment]
因为是私有的属性

**Comment by h3clikejava** [comment]
> 

请问怎么拿到群聊里面说话的人名字呢？现在收到的群消息Sender对象是群(sender.Nikename是群名字)，msg.Context拿到的是内容，怎么知道是谁(群里的哪个人)发的？
