### ISSUE TITLE
每天晚上自动掉线

### ISSUE THREAD

**Issue by wtf-boy** [eatmoreapple/openwechat#25]
2021/07/01 00:46:02 exit with : Get "https://webpush.wx.qq.com/cgi-bin/mmwebwx-b
in/synccheck?_=1625071562&deviceid=e808322456474126&r=1625071562&sid=40nGHnRY5FJ
YuVzQ&skey=%40crypt_b940ac04_4217d3d7187588aa0b977f013429122c&synckey=1_73832721
6%7C2_738327218%7C3_738327163%7C11_738327174%7C19_13599%7C201_1625070781%7C203_1
625059066%7C206_101%7C1000_1625057416%7C1001_1625057420&uin=47260****": net/http
: HTTP/1.x transport connection broken: malformed HTTP status code "0"

2021/07/02 00:19:11 exit with : Get "https://webpush.wx.qq.com/cgi-bin/mmwebwx-b
in/synccheck?_=1625156351&deviceid=e473567460463755&r=1625156351&sid=SV82nd8KfFh
4ZhQK&skey=%40crypt_b940ac04_16e01eeef2f77d0cbc7c4c971fdbdc94&synckey=1_73832724
3%7C2_738327394%7C3_738327163%7C11_738327174%7C19_13614%7C201_1625152664%7C203_1
625059066%7C206_101%7C1000_1625143120%7C1001_1625143820&uin=47260****": net/http
: HTTP/1.x transport connection broken: malformed HTTP status code "0"

**Comment by eatMoreApple** [comment]
试试重新设置`Bot.GetMessageErrorHandler`, 默认行为是直接退出

**Comment by suntong** [comment]
@eatMoreApple, I'm getting exactly that as well (see below), can you show us how to properly workaround it in `Bot.GetMessageErrorHandler` please? As I'm thinking that everybody would ask the same question as well. thx!

```
2021/07/15 03:42:26 exit with : Get "https://webpush.web.wechat.com/cgi-bin/mmwebwx-bin/synccheck?_=1626334946&deviceid=e518...&r=1626...&sid=jzT...&skey=%40crypt_6017...&synckey=1_696...&uin=516...": net/http: HTTP/1.x transport connection broken: malformed HTTP status code "0"
2021年 07月 15日 星期四 03:42:26 EDT
```

**Comment by eatMoreApple** [comment]
```
bot := openwechat.DefaultBot()
// bot := openwechat.DefaultBot(openwechat.Desktop) // 桌面模式，上面登录不上的可以尝试切换这种模式
var count int32
bot.GetMessageErrorHandler = func(err error) {
        // do your owner idea here
        atomic.AddInt32(&count, 1)
        // 如果发生了三次错误,那么直接退出
        if count == 3 {
	        bot.Logout()
        }
}
```

**Comment by suntong** [comment]
Ah, thx, that's a good starting point.

**Comment by suntong** [comment]
Hmm... Would you be so kind as to explain why `atomic.AddInt32` instead of `count++` please?

I want to log the last time 错误发生, and increase `count` _**only if**_ 错误发生 within say 1 minute, else will start from `1` again. I'm wondering what kind of  `atomic` operation I need to store and do the diff on the time of 错误发生. (and demo code appreciated of course, :) )

Thanks a lot.

**Comment by eatMoreApple** [comment]
后台会额外有一个`goroutine`跟wx服务器保持连接，如果没有别的地方操作`count`, 用`count++`也是可以的，不会有线程安全问题。

**Comment by suntong** [comment]
Thanks @eatMoreApple, gotya!

Just logging another error that I got, apart from the above `malformed HTTP status code "0"` -- 

`Err="base response ret code 3"`

I searched this whole repo but didn't find such error text, so I'm wondering where does it come from.
Oh, got it, returned from `bot.HotLogin(reloadStorage)`. 

Now, it's a challenge how to deal with all of above errors within `bot.GetMessageErrorHandler`...

**Comment by suntong** [comment]
I tried that strategy, but seems that the `malformed HTTP status code "0"` error means the account connection status has changed and it is not recoverable. Will check more on that...

**Comment by suntong** [comment]
>         if count == 3 {
> 	        bot.Logout()
>         }

Can `bot.Logout()` actually stop the program?

Here is my code:
https://github.com/suntong/owc-insight/blob/25915c4d35480e364a6ca8db720daf084545cada/main.go#L87-L97  
It is doing:

```go
		// 如果发生了三次错误,那么直接退出
		if count == 3 {
			bot.Logout()
		}
```

However, take a look at my log:

![image](https://user-images.githubusercontent.com/422244/126903369-d7afd759-848a-4205-acd3-000e29903af0.png)

It seems when `count == 3` and `bot.Logout()` is called, it actually doesn't have any effect, at least it didn't stop the program.

**Comment by li-xunhuan** [comment]
> Thanks @eatMoreApple, gotya!
> 
> Just logging another error that I got, apart from the above `malformed HTTP status code "0"` --
> 
> `Err="base response ret code 3"`
> 
> I searched this whole repo but didn't find such error text, so I'm wondering where does it come from.
> Oh, got it, returned from `bot.HotLogin(reloadStorage)`.
> 
> Now, it's a challenge how to deal with all of above errors within `bot.GetMessageErrorHandler`...

关于`ret code 3`，我找到了一个有意思的东西，获取有帮助。
![微信图片_20210726143122](https://user-images.githubusercontent.com/10476982/126943475-dfebf8a3-b511-4021-a680-37bb27c3fe87.png)

**Comment by li-xunhuan** [comment]
@suntong 如果不介意，你可以加我微信，我们拉个微信群讨论。

If you don’t mind, you can add me to WeChat , we can discussion in WeChat group.

**Comment by suntong** [comment]
好啊，怎么加？
另外，上文的链接？

**Comment by li-xunhuan** [comment]
> 好啊，怎么加？
> 另外，上文的链接？

微信号：     _Elixir

**Comment by li-xunhuan** [comment]
> 好啊，怎么加？
> 另外，上文的链接？

链接： https://github.com/moontide/WeChatBotEngine/issues/5

**Comment by shangdev** [comment]
我也遇到了，运行过程中自动退出，如下：
![image](https://user-images.githubusercontent.com/15621520/127729983-e82568bf-5a13-430b-a222-ec1ba6d1680b.png)

you有什么好的解决办法吗 @eatmoreapple

**Comment by eatmoreapple** [comment]
> 我也遇到了，运行过程中自动退出，如下：
> ![image](https://user-images.githubusercontent.com/15621520/127729983-e82568bf-5a13-430b-a222-ec1ba6d1680b.png)
> 
> 有什么好的解决办法吗 @eatmoreapple

暂时没有，群里的大佬们在想办法..

**Comment by MrGameplayer** [comment]
> > 我也遇到了，运行过程中自动退出，如下：
> > ![image](https://user-images.githubusercontent.com/15621520/127729983-e82568bf-5a13-430b-a222-ec1ba6d1680b.png)
> > 有什么好的解决办法吗 @eatmoreapple
> 
> 暂时没有，群里的大佬们在想办法..
我也遇到这个问题了，查了好久查不出来什么毛病，大佬能拉我进群吗@eatmoreapple

**Comment by eatmoreapple** [comment]
加我微信 `EatMoreApple` @MrGameplayer
