### ISSUE TITLE
【feat】添加日志模块

### ISSUE THREAD

**Issue by wenyoufu** [eatmoreapple/openwechat#250]

**Comment by wenyoufu** [comment]
请reviewmr:https://github.com/eatmoreapple/openwechat/pull/252

**Comment by wenyoufu** [comment]
功能背景：1.从一个系统完备性的角度讲，日志记录是必要的 2.该模块应用在该项目内部，有助于问题的定位，程序代码难免有许多bug，代码中关键性埋点有助于问题的定位

**Comment by eatmoreapple** [comment]
让用户用自己喜欢的方式接入，不强制使用。
