### ISSUE TITLE
如何获取当前消息的群名称？

### ISSUE THREAD

**Issue by yudan215** [eatmoreapple/openwechat#253]
如何获取当前消息的群名称？

**Comment by eatmoreapple** [comment]
获取消息的发送者
sender, err := msg.Sender()
如果是群聊消息，该方法返回的是群聊对象(需要自己将User转换为Group对象)

**Comment by yudan215** [comment]
谢谢

**Comment by Yeeyao** [comment]
> 获取消息的发送者 sender, err := msg.Sender() 如果是群聊消息，该方法返回的是群聊对象(需要自己将User转换为Group对象) sender.Nickname

请问这里怎么转换呢？
