### ISSUE TITLE
Error: invalid host

### ISSUE THREAD

**Issue by suntong** [eatMoreApple/openwechat#26]
Following up on #11 & #12, 

Same code from #9 is still not working for me, despite that I updated `openwechat` just now. 
Neither of my two accounts is working for me. 

- For the first one I got cannot use WX desktop from my phone, while 
- for the second one, I'm getting this:

```
openwechat
访问下面网址扫描二维码登录
https://login.weixin.qq.com/qrcode/gfVccJbBsA==
invalid host
```

So still badly need #12 to understand what's going on and where does that `invalid host` error coming form. thx

**Comment by eatMoreApple** [comment]
请更新最新的版本重试

**Comment by eatMoreApple** [comment]
`invalid host`是因为之前代码会去做host匹配, 匹配的类型有限,没有匹配带才会出这个错误，现在是自动生成。你可以再试一下.

**Comment by suntong** [comment]
Yeah, sorry for responding late, I was planning to test it but get detoured. Will test today. thx

**Comment by suntong** [comment]
成功了，竟然😳
为这个我已经经历了太多的磨难了
这一次成功来的有点太过突然
突然的都有些超乎想象啊！
不敢接受，这就是事实——这个竟然从今天起就能用了😊😭😭😭

太感谢了，老大🙏🙏🙏
