### ISSUE TITLE
【doc】请修改doc描述

### ISSUE THREAD

**Issue by wenyoufu** [eatmoreapple/openwechat#260]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/19179965/217564125-ab9572fe-ae3c-4034-be2c-f0a425cf7913.png">

参见：【bug-fix】修改不在通讯录无法获取群组的bug 解决方案：程序运行后，如果群组（不在通讯录中）,发送过任意消息，则更新群组(解决bug#225)

**Comment by eatmoreapple** [comment]
好的，谢谢大哥提醒

**Comment by eatmoreapple** [comment]
已修改，如果您觉得哪里有问题，可以通过修改source下面的markdown文件来实现文档的更新哦。
