### ISSUE TITLE
社死了兄弟们，我不知道微信群也会自动回复

### ISSUE THREAD

**Issue by anccy** [eatmoreapple/openwechat#269]
开启自动回复以后一不留神，发现自己竟然在群里自动回复别人？？

 我以在以下群聊社死😭

部门群
物业群
跳舞同好群
薅羊毛广告群

**Comment by eatmoreapple** [comment]
哈哈哈哈，你回复了啥？

**Comment by anccy** [comment]
> 哈哈哈哈，你回复了啥？

就说不在线请留言什么的：（

**Comment by yxw21** [comment]
哈哈哈，让我笑一会
