### ISSUE TITLE
求助，一直无法启动

### ISSUE THREAD

**Issue by TBSAAA** [eatmoreapple/openwechat#275]
os.Remove storage.json error: remove storage.json: no such file or directory
在mac上运行，扫码成功后，一直提示这个错误。我没写过go语言，我顺着执行流程看了一下，好像storage.json这个文件没有生成，请问是什么原因造成的啊？

**Comment by eatmoreapple** [comment]
你这是哪里的项目？

**Comment by TBSAAA** [comment]
·····有个哥们fork了你的项目，我顺着fork找过来，原来他在你写的基础上做了修改，我没看到他们的提交记录，我以为代码一样的，不好意思啊
