### ISSUE TITLE
msg.ReplyText() not working

### ISSUE THREAD

**Issue by suntong** [eatMoreApple/openwechat#28]
Using code from #9 with:

```go
	// 注册消息处理函数
	bot.MessageHandler = func(msg *openwechat.Message) {
		if msg.IsText() {
			if msg.Content == "ping" {
				msg.ReplyText("pong")
				fmt.Println("回文本消息", msg.Content)
			} else  {
				fmt.Println("收到文本消息", msg.Content)
			}
		}
	}
```

When I got `ping` (sent from myself), I can see "`回文本消息 ping`" being printed on console, but I was never able to get that `pong` back.

**Comment by eatMoreApple** [comment]
请问你是不是自己发送的`ping`给别人？，`Reply`系列函数是回复消息给发送方，此时的发送方是你自己，自己是不能回复消息给自己的，你用另外一个号发送消息给自己试试。我测试是正常的。

**Comment by eatMoreApple** [comment]
请问你是不是自己发送的`ping`给别人？，`Reply`系列函数是回复消息给发送方，此时的发送方是你自己，自己是不能回复消息给自己的，你用另外一个号发送消息给自己试试。我测试是正常的。

**Comment by suntong** [comment]
> Reply系列函数是回复消息给发送方，此时的发送方是你自己，自己是不能回复消息给自己的

Ah,gotya! Thanks!
