### ISSUE TITLE
有封号风险

### ISSUE THREAD

**Issue by dusty-cjh** [eatmoreapple/openwechat#280]
前几天用了下，然后昨天直接封号了。学习了下法律知识才放出来

**Comment by eatmoreapple** [comment]
是的大哥，现在抓的有点紧

**Comment by zhuang1234** [comment]
真是的，为啥wechat不让搞机器人呀！就不能好好学学人家tg的那种开放态度嘛，哎，无奈

**Comment by smithyj** [comment]
> 

因为我们在美国，享有自由、民主，所以wechat才这样做的

**Comment by zhuang1234** [comment]
真的不懂你这种优越感哪里来的，润就润了，没必要再说那么多没必要的话

**Comment by stevenlee87** [comment]
@dusty-cjh 为什么会封号呢？

**Comment by dusty-cjh** [comment]
仓库实现的问题，可以被TX审查到，慎用。

**Comment by smithyj** [comment]
> 真的不懂你这种优越感哪里来的，润就润了，没必要再说那么多没必要的话

看不懂回复？你现在不在美国吗？

**Comment by zhuang1234** [comment]
对不起不在，这只是一个go的sdk而已，和你在不在美国有何关系？
