### ISSUE TITLE
判断消息是否为@消息的逻辑问题：好像并未考虑被引用内容中的包含@的情况

### ISSUE THREAD

**Issue by yinqishuo** [eatmoreapple/openwechat#288]
在message.go 文件480行Message.isAt，函数检测自己被是否被@的原理是消息中是否包含【@自己的名字】，但是有一种特殊情况是引用内容中包含【@自己的名字】。
例如在群聊中有如下对话（假设被@机器人会回复）：
我：@Robot  你好！
Robot：你好                                                              -----检测到自己被@会回复
我：hahaha。[@Robot  你好!]                                  -----[@Robot  你好!]代指微信被引用的内容  
Robot：哈哈                                                              -----检测到文本中包含@Robot，依旧会回复，所以有问题

所以我觉得检测自己被是否被@的方法应该是：首先去除被引用的内容，再再消息中检测是否包含【@自己的名字】

刚接触go，不知道对不对，望采纳。

**Comment by eatmoreapple** [comment]
是的，你说的很对，哈哈哈
