### ISSUE TITLE
基于微信什么协议实现的？

### ISSUE THREAD

**Issue by FishMan132** [eatmoreapple/openwechat#289]

**Comment by eatmoreapple** [comment]
网页版微信，http

**Comment by Mr-LiuDC** [comment]
> 网页版微信，http

@eatmoreapple  请问桌面模式也是基于Web协议吗？

**Comment by Mr-LiuDC** [comment]
@eatmoreapple 
初步浏览了一下代码，发现是基于 UOS Electron 套壳。

但是没搞懂是怎么套壳的，可以赐教下吗？

最近在研究微信聊天机器人，对于像微信 Pad 协议， Windows 协议等有点蒙。
