### ISSUE TITLE
Failed to 获取最新的好友

### ISSUE THREAD

**Issue by suntong** [eatMoreApple/openwechat#29]
```go
friends, err := self.Friends(true)
```

> Friends：可接受bool值来判断是否获取最新的好友

I'm using `self.Friends(true)` but still unable to 获取**最新**的好友 -- The friend list that I got is still old, even after my friend-editing has done for 1+ hours.

**Comment by eatMoreApple** [comment]
你好，这个功能我测试的也是正常的，几乎是立马就更新，没有发生您说的超过了1个多小时依然是旧数据。如果您是打印查看的`Friends`列表，请注意列表里显示的是用户的昵称，而非备注名，需要被查看的用户自己去改昵称才能看到变化，或者您可以拿到需要查看的用户对象，主动查看备注，下面是我测试的代码，您可以参考下
```
bot.MessageHandler = func(msg *openwechat.Message) {
        if msg.IsText() {
            if msg.Content == "ping" {
                msg.ReplyText("pong")
                user, _ := msg.Bot.GetCurrentUser()
                // 先去手机上修改,然后在发送ping触发这个事件查看
                fmt.Println(user.Friends(true))
            } else {
                fmt.Println("收到文本消息", msg.Content)
            }
        }
    }
```

**Comment by suntong** [comment]
Oh, thanks for the reply. Sorry my machine doesn't have Chinese input yet, so I have to write in English. 

So, 

> 请注意列表里显示的是用户的昵称，而非备注名，需要被查看的用户自己去改昵称才能看到变化

Oh, that's why thanks for the explanation! Thanks!
