### ISSUE TITLE
这个开源相当于“微信登录客户端”吗

### ISSUE THREAD

**Issue by lifa1225** [eatMoreApple/openwechat#3]
是用于登录个人微信的吗？如果是的话，可以通过这个方式给指定用户发送微信消息（如生产环境报警信息），替代掉公众号或者企业微信？

**Comment by eatMoreApple** [comment]
支持给指定的好友，群组群发消息，可以自定义实现的机器人报警的功能。但是存在部分用户无法登陆的情况，可以尝试使用Desktop和Normal的模式尝试登陆。
