### ISSUE TITLE
List of projects using openwechat

### ISSUE THREAD

**Issue by suntong** [eatmoreapple/openwechat#30]
Hi @eatMoreApple, 

Do you think it is a good idea to list all open source projects that are using `openwechat` at the end of Readme or in wiki? 

If OK, I can get the ball rolling by submit the first PR.

cheers

**Comment by eatMoreApple** [comment]
感谢您的提议，我不会搞这个，先让我研究一下怎么玩，哈哈

**Comment by suntong** [comment]
Oh, I'm not planning anything fancy, as there are only _two_ repos that I found using `openwechat` at the moment within github. 

I think the best approach _for now_ is, 

- mention something like "For a list of open source projects that are using `openwechat`, check out the wiki entry here" in Chinese, and
- create a wiki entry that list them in alphabetic order in point forms

This would be the easiest way to get started, and most importantly, the easiest way to get people involved as well :).

**Comment by eatMoreApple** [comment]
可以的

**Comment by suntong** [comment]
Was about doing it, but found myself unable to edit wiki. Most probably I'm not a collaborator yet, as the wiki _"restrict editing to collaborators only"_.

Will push some changes and see if my status changes.

**Comment by suntong** [comment]
> Will push some changes and see if my status changes.

Hi @eatMoreApple, I just checked, after done some pushing-changes, I'm not a collaborator yet, i.e., unable to edit wiki.

Shall I wait for some more time for the magic to happen, or you can directly change my status to  be a collaborator?

**Comment by suntong** [comment]
Oh, found out that I'm already a collaborator, but still not able to edit wiki.

@eatMoreApple, please set/relax the wiki rule to "restrict editing to collaborators only". thx.

**Comment by eatmoreapple** [comment]
OK，好了，您再试一下

**Comment by suntong** [comment]
👌!
🙏!
