### ISSUE TITLE
Alive方法无法正常判断当前用户是否在线

### ISSUE THREAD

**Issue by itxiaolin** [eatmoreapple/openwechat#324]
机器人异常退出后，调用Alive方法还是一样返回true

**Comment by eatmoreapple** [comment]
能看看是怎么异常退出的吗？

**Comment by itxiaolin** [comment]
应该是长时间没接收到消息掉线问题，我有一个监听器，每秒都会查一次alive的状态，返回还是true，但是bot一直在刷SyncCheckCallback心跳回调函数，下次复现再贴一下日志

**Comment by itxiaolin** [comment]
bot.SyncCheckCallback = func(resp openwechat.SyncCheckResponse) {
	logger.Info( "心跳函数，", zap.String("uuid", bot.UUID()), zap.String("RetCode", resp.RetCode))
}
在代码中，我设置了心跳函数，日志也正常，但机器人已经掉线了，我的监听器中调用了bot.Alive()返回了true
2023/04/13-13:53:29.278 INFO    logger/logger.go:21     心跳函数，      {"uuid": "YcmqUNlv9g==", "RetCode": "0"}
2023/04/13-13:53:29.422 INFO    logger/logger.go:21     心跳函数，      {"uuid": "YcmqUNlv9g==", "RetCode": "0"}
2023/04/13-13:53:29.573 INFO    logger/logger.go:21     心跳函数，      {"uuid": "YcmqUNlv9g==", "RetCode": "0"}

**Comment by itxiaolin** [comment]
有没有一个方法是去调用远程微信接口，如果掉线了会返回错误内容的？

**Comment by eatmoreapple** [comment]
有个小哥提交了个pr，看看是否修复了你这个问题

**Comment by itxiaolin** [comment]
最新版好像删了SetUUID方法，怎么手动登录

**Comment by itxiaolin** [comment]
似乎已经找到了替换方法WithUUIDOption

**Comment by chimojiacai** [comment]
> 似乎已经找到了替换方法WithUUIDOption

设置好WithUUIDOption，如何传递参数啊，
`	loginOption := openwechat.NewRetryLoginOption()
	option := openwechat.WithUUIDOption(uuid)
	//option.Prepare(bot)
	//loginOption.Prepare(bot)
	
	if err := bot.HotLogin(reloadStorage, loginOption); err != nil {
		return err
	}`
