### ISSUE TITLE
我运行起来无法收到gpt的响应

### ISSUE THREAD

**Issue by Yellow-eq** [eatmoreapple/openwechat#328]
2023/04/14 16:45:17 Received User Async Text Msg : 1
2023/04/14 16:45:17 request gtp json string : {"model":"text-davinci-003","prompt":"1","max_tokens":2048,"temperature":0.7,"top_p":1,"frequency_penalty":0,"presence_penalty":0}
2023/04/14 16:45:38 gtp request error: Post "https://api.openai.com/v1/completions": dial tcp 108.160.170.44:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by Yellow-eq** [comment]
我把clash for windows的vpn开着的，网页访问gpt没问题

**Comment by eatmoreapple** [comment]
您串台了

**Comment by itxiaolin** [comment]
因为你的ide不走你vpn的代理

**Comment by Yellow-eq** [comment]
> 您串台了

不好意思，串台了
