### ISSUE TITLE
Need message types

### ISSUE THREAD

**Issue by suntong** [eatMoreApple/openwechat#33]
Following up on
https://github.com/eatMoreApple/openwechat/issues/32#issuecomment-883871113

I wish we can have a way to get the WX message original types. The https://github.com/eatMoreApple/openwechat/issues/32#issuecomment-883871113 has listed many message types in WX raw format, like 3, 5, 51, 54 etc. 

I want to be able to print out "Received message type = %s", which prints _directly_ 3, 5, 51, 54 etc, instead of I have to query one by one, is it text? is it image? is it map? etc, etc.

THX!

**Comment by suntong** [comment]
One important reason is that, the `type==5` message example listed in https://github.com/eatMoreApple/openwechat/issues/32#issuecomment-883871113, I believe even if I have gone through ***all*** the existing predefined checks, like is it text? is it image? is it map? etc, It'll _still_ be missed because its type has not yet been predefined by `openwechat` yet.

**Comment by suntong** [comment]
Found it in the source. The one I need is,

https://github.com/eatMoreApple/openwechat/blob/b2178d32a28d61fb195adbc1575d574afbaed49f/message.go#L486

and

https://github.com/eatMoreApple/openwechat/blob/b2178d32a28d61fb195adbc1575d574afbaed49f/message.go#L23
or
https://github.com/eatMoreApple/openwechat/blob/b2178d32a28d61fb195adbc1575d574afbaed49f/message.go#L20

Don't know exactly which one is though.

**Comment by eatMoreApple** [comment]
您可以访问`https://res.wx.qq.com/a/wx_fed/webwx/res/static/js/index_c7d281c.js`  从第6987行开始就可以看到所有的消息类型

**Comment by eatMoreApple** [comment]
您可以访问`https://res.wx.qq.com/a/wx_fed/webwx/res/static/js/index_c7d281c.js`  从第6987行开始就可以看到所有的消息类型

**Comment by eatMoreApple** [comment]
访问`Message. MsgType `属性就可以拿到当前的消息类型了

**Comment by suntong** [comment]
Gotcha. THX!
