### ISSUE TITLE
OnGroupByGroupName() or OnGroupByGroupID()

### ISSUE THREAD

**Issue by suntong** [eatmoreapple/openwechat#34]
根据群名是否匹配的消息处理函数，只能注册 `OnGroupByGroupName`. But the problem is that sometime the group changes its name from time to time. 

The Group ID never change, right? If so, that would be a better/safer option.

**Comment by eatMoreApple** [comment]
可以的啊，只要当前的会话不断开，那么`GroupId`（UserName）就是唯一的，您可以使用`RegisterHandler`来注册自己的匹配规则
参考
```
// 注册处理消息类型为Text的处理函数
func (m *MessageMatchDispatcher) OnText(handlers ...MessageContextHandler) {
	m.RegisterHandler(func(message *Message) bool { return message.IsText() }, handlers...)
}
```
