### ISSUE TITLE
可以支持主动发送消息吗

### ISSUE THREAD

**Issue by LingMessy** [eatmoreapple/openwechat#344]
好像只能回复消息没有主动发送消息的功能，例如实现定时自动发消息通知的功能就需要主动发送消息

**Comment by eatmoreapple** [comment]
有的，看文档，地址在readme里面

**Comment by LingMessy** [comment]
> 有的，看文档，地址在readme里面

方便说一下具体的方法吗，我只找到msg.ReplyXX的方法，这种方法是需要接收到一个Message对象才可以使用的吧

**Comment by LingMessy** [comment]
哦哦，我找到了，谢谢回复，不好意思之前没仔细看，应该是SendTextToFriend，麻烦你了
