### ISSUE TITLE
添加HttpHook打印日志启动失败

### ISSUE THREAD

**Issue by ViaDroid** [eatmoreapple/openwechat#346]
添加自定义的HttpHook, 打印请求后的body, 启动会失败

HttpLogHook
```go
type HttpLogHook struct {
}

func (logHook *HttpLogHook) BeforeRequest(req *http.Request) {
	log.Printf("Request URL: %v\n", req.URL)
}

func (logHook *HttpLogHook) AfterRequest(resp *http.Response, err error) {
	if err != nil {
		return
	}

	bs, err := io.ReadAll(resp.Body)
	if err != nil {
		return
	}
	log.Printf("Resp.body: %s\n", bs)
}
``` 

添加到bot
```go
bot.Caller.Client.AddHttpHook(&tools.HttpLogHook{})
```

**Comment by eatmoreapple** [comment]
你把body都读完了，后面的就读不到了

**Comment by ViaDroid** [comment]
嗯，我本地简单改了一下client.go代码, 暂时先用着，
感觉这块后面可以优化一下

`
func (c *Client) do(req *http.Request) (*http.Response, error) {
	for _, hook := range c.HttpHooks {
		hook.BeforeRequest(req)
	}
	var (
		resp *http.Response
		err  error
	)
	for i := 0; i < c.MaxRetryTimes; i++ {
		resp, err = c.client.Do(req)
		if err == nil {
			break
		}
	}
	if err != nil {
		err = fmt.Errorf("%w: %s", NetworkErr, err.Error())
	}
	//Add start
	bs, _ := io.ReadAll(resp.Body)
	resp.Body.Close()	
	resp.Body = io.NopCloser(bytes.NewBuffer(bs))

	var respCpy = new(http.Response)
	*respCpy = *resp
	respCpy.Body = io.NopCloser(bytes.NewBuffer(bs))
       //add end

	for _, hook := range c.HttpHooks {
		hook.AfterRequest(respCpy, err) //modify
	}
	return resp, err
}
`

**Comment by ViaDroid** [comment]
上面思路想复杂了，改下Hook func就可以了：

```go
func (logHook *HttpLogHook) AfterRequest(resp *http.Response, err error) {
	if err != nil {
		return
	}

	bs, _ := io.ReadAll(resp.Body)
	resp.Body.Close()
	resp.Body = io.NopCloser(bytes.NewBuffer(bs))

	log.Printf("Response: %s\n", bs)
}
```

解决^_^
