### ISSUE TITLE
这个回调函数的用法怎么理解

### ISSUE THREAD

**Issue by auqf** [eatmoreapple/openwechat#347]
![image](https://github.com/eatmoreapple/openwechat/assets/8895540/8b79a89a-80a9-4ee4-9c1d-c0fb5792d8cd)
图中的这个地方的用法怎么理解啊，类型只是定义了一个空函数，另外一边也没调用函数，且没有返回值啊

**Comment by eatmoreapple** [comment]
[点击查看](https://baike.baidu.com/item/%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0/7545973?fr=aladdin)

它字多，跟它混。
