### ISSUE TITLE
New openwechat org

### ISSUE THREAD

**Issue by suntong** [eatmoreapple/openwechat#35]
Reopen from #20, 

I still think it is a good idea to create a new openwechat GH organization, put openwechat under it, and collect all different sample/demo projects there as well.

So the next person who comes along, can just pick and choose which sample/demo projects to start with, or know which demo projects to turn to troubleshoot (without the need to hunt for it), like having more insight into the login handshaking.

**Comment by suntong** [comment]
My owc-insight, OpenWeChat Insight, was meant for that. 

The reason I now think it is necessary is partly because, 

In my Emacs lsp-log buffer, I saw the error message of

```
imports fixes: AllImportsFixes: /home/me/l/gg/suntong/owc-insight/main.go:15:16: expected 'STRING', found string (and 20 more errors)
	file="/home/me/l/gg/suntong/owc-insight/main.go"
```

which is pointing to (15:16):

```
	"github.com/eatMoreApple/openwechat"
	 -------------^
```

I.e., my [Emacs lsp](https://github.com/suntong/emacs.d#ide-out-of-the-box) thinks something wrong with the name of eatMoreApple, 

Don't know how valid it is ,and if the unusual uppercase package name has anything to do with the problem.

**Comment by suntong** [comment]
FYI, from https://github.com/xo/xo/issues/281#issuecomment-881071374

> I would like to point out that idiomatically, Go package names should be all lower case.

**Comment by eatMoreApple** [comment]
这样吗？..... 确实我这个名字取的不太好，在go  cache文件里面都有符号出现..

**Comment by eatMoreApple** [comment]
这样吗？..... 确实我这个名字取的不太好，在go  cache文件夹里面都有符号出现..

**Comment by suntong** [comment]
Let's do it sooner than later! thx!

**Comment by electricbubble** [comment]
> > I would like to point out that idiomatically, Go package names should be all lower case.

哈哈哈, 确实, 我就是应该这原因把 `username` 全小写了

**Comment by suntong** [comment]
@eatmoreapple 
老大对这个建议怎么看？
近期内会做吗？
需要我帮什么忙吗？

**Comment by eatmoreapple** [comment]
包名已经都转小写了

**Comment by eatmoreapple** [comment]
> @eatmoreapple
> 老大对这个建议怎么看？
> 近期内会做吗？
> 需要我帮什么忙吗？

这个我不太会玩，该怎么做呢

**Comment by suntong** [comment]
Oh, OK. See

**Creating a new organization from scratch**  
https://help.github.com/articles/creating-a-new-organization-from-scratch/

But I've done that for you and invited you as the owner. 

The next step is important -- Transferring a repository. Do

- `git pull` locally, as local backup
- follow Transferring a repository @ https://help.github.com/articles/transferring-a-repository/
- fix git remote or do a brand new `git clone` from new repo

This is how I'm transferring mine FYI:
![image](https://user-images.githubusercontent.com/422244/127177885-1b1d2837-064b-4851-8b99-b6da4e5e6ef4.png)

**Comment by suntong** [comment]
BTW, GH will redirect all old request (http / git) to new place. E.g., https://github.com/suntong/owc-insight/ still works, but now redirected to https://github.com/go-openwechat/owc-insight.
