### ISSUE TITLE
关于接受和发送“合并类型消息”的功能咨询

### ISSUE THREAD

**Issue by zer0yu** [eatmoreapple/openwechat#350]
您好，我想咨询一下如果我想接收和转发“合并转发”这种类型的消息应该怎么处理呢？

![1801684125008_ pic](https://github.com/eatmoreapple/openwechat/assets/16551733/e588467e-97e8-48b5-992f-9ba2d7697dc1)

**Comment by eatmoreapple** [comment]
你好，网页版微信是不支持解析这种消息格式的。
[收到一条网页版微信暂不支持的消息类型，请在手机上查看]

**Comment by zer0yu** [comment]
原来是这样子，感谢回复

**Comment by zer0yu** [comment]
@eatmoreapple 开发大大您好，我还想问下小程序消息如何转发呢？比如别人发我一个腾讯文档的小程序消息，这种是否可以转发呢？

**Comment by eatmoreapple** [comment]
你好，转发不了的。

**Comment by zer0yu** [comment]
Get
