### ISSUE TITLE
热登陆 cookie 失效

### ISSUE THREAD

**Issue by suntong** [eatMoreApple/openwechat#36]
Following on https://github.com/eatMoreApple/openwechat/issues/7#issuecomment-839752574, for my

`Error: not login check`

https://github.com/eatMoreApple/openwechat/blob/b2178d32a28d61fb195adbc1575d574afbaed49f/items.go#L155-L156

I saw that 热登陆 cookie only get updated when trying to 获取新的消息:

> 更新SyncKey并且重新存入storage
https://github.com/eatMoreApple/openwechat/blob/b2178d32a28d61fb195adbc1575d574afbaed49f/bot.go#L258-L259

which is called from 

https://github.com/eatMoreApple/openwechat/blob/b2178d32a28d61fb195adbc1575d574afbaed49f/bot.go#L224-L240

The problem is that when an account doesn't have any new messages for a prolong time, the cookie will 失效, because it hasn't been updated for a prolong time.

Do you think saving (重新存入storage) it periodically in 轮训请求 will prolong its life span?

**Comment by suntong** [comment]
Ah, no! --  重新存入storage 的 SyncKey comes from `resp.SyncKey`. 

Hmm...

**Comment by eatMoreApple** [comment]
额，这个问题是一直存在的，但我也找不到问题在哪里，有效期好像只有23个小时，有空再研究一下。

**Comment by suntong** [comment]
I got much _much_ fewer than that -- only about a few minutes. 

But I've got an idea. Let me run my program overnight and see...

**Comment by suntong** [comment]
> But I've got an idea. Let me run my program overnight and see...

Yeah, it basically works, extend my connection from merely a few minutes to hours, until get kicked from the server side -- #25. 

For details, check out the `openwechat` sample/practical get-start-code that I'm preparing --
https://github.com/suntong/owc-insight/blob/devtest/UseMine/devtest/UseMine/main/README.md#features

**Comment by suntong** [comment]
Close it for now.
