### ISSUE TITLE
OnLogout()?

### ISSUE THREAD

**Issue by suntong** [eatmoreapple/openwechat#37]
Need `OnLogout()` callback (回调函数) so that people can do their own clean up.

Comments?

**Comment by eatMoreApple** [comment]
有的，`Bot.LogoutCallBack`

**Comment by suntong** [comment]
Oh, great!

Hmm... All other callbacks are called OnSomething,  
shall `LogoutCallBack` do the same and be called `OnLogout` instead?

**Comment by eatmoreapple** [comment]
添加了

**Comment by suntong** [comment]
https://github.com/eatmoreapple/openwechat/commit/5120404ba790bf6be8f1b9aa4131af259ccaf189
