### ISSUE TITLE
What are these AppIds?

### ISSUE THREAD

**Issue by suntong** [eatMoreApple/openwechat#4]
What are these AppIds?

https://github.com/eatMoreApple/openwechat/blob/d0444bc954679b1f8da97e9289996be0b8ae438a/global.go#L16

https://github.com/eatMoreApple/openwechat/blob/d0444bc954679b1f8da97e9289996be0b8ae438a/global.go#L128

Do we need to change them on our ends? 

Thx

**Comment by eatMoreApple** [comment]
You need't to change them, visit  [https://res.wx.qq.com/a/wx_fed/webwx/res/static/js/index_c7d281c.js](https://res.wx.qq.com/a/wx_fed/webwx/res/static/js/index_c7d281c.js) could find those code.

**Comment by suntong** [comment]
thanks!
