### ISSUE TITLE
如何获取合并转发的消息的具体内容

### ISSUE THREAD

**Issue by smellyTwiceMonkey** [eatmoreapple/openwechat#403]
如题，当收到合并转发的消息时，

消息类型是  
MsgTypeApp            MessageType = 49    // APP消息 

消息内容是
Content: "该类型暂不支持，请在手机上查看"

**该如何获取消息的具体内容？**

**Comment by eatmoreapple** [comment]
这个获取不到的哦

**Comment by smellyTwiceMonkey** [comment]
> 这个获取不到的哦

好的，谢谢！
