### ISSUE TITLE
改用户备注问题

### ISSUE THREAD

**Issue by peifengll** [eatmoreapple/openwechat#412]
SetRemarkName貌似已经失效,本来的想法是自动给好友设置唯一备注
能获取这个用户的类似唯一标识一样的东西吗，比如微信号之类的

**Comment by eatmoreapple** [comment]
用avatarID,  但是用户换了头像之后，这个值就变了

**Comment by peifengll** [comment]
> 用avatarID, 但是用户换了头像之后，这个值就变了

好的，谢谢啦
