### ISSUE TITLE
功能请求：希望下载附件功能，添加IsFile()功能

### ISSUE THREAD

**Issue by edxi** [eatmoreapple/openwechat#415]
我要写个程序时朋友传我zip时，可以自动下载然后解压放到我自己的目录里

目前没有IsFile()，
只能通过m.AppMsgType == AppMsgTypeAttach来判断，然后使用GetFile。

目前GetFile()会用HasFile()判断是不是文件。
HasFile里判断是否为附件的方式是m.IsMedia() && m.AppMsgType == AppMsgTypeAttach。

大佬为啥不单独做个只针对附件的呢？。。。

**Comment by eatmoreapple** [comment]
好的哥，给您加上
