### ISSUE TITLE
FromUserName and ToUserName

### ISSUE THREAD

**Issue by suntong** [eatmoreapple/openwechat#42]
I tried to print out `FromUserName` and `ToUserName` from the  `Message` struct

https://github.com/eatmoreapple/openwechat/blob/5120404ba790bf6be8f1b9aa4131af259ccaf189/message.go#L45-L49

but all I got is:

`from=@@d68e3047e7b651cca.....bae9096c1780d128478 to=@821ee97c61a729....a9d6b7760f173644070b`

why it's like that, instead of the actual WX User Names?

**Comment by eatmoreapple** [comment]
这个是当前会话的用户的唯一身份标识符，仅在当前会话有效，断开连接后就失效了。

**Comment by eatmoreapple** [comment]
昵称用`NickName`属性获取

**Comment by suntong** [comment]
Hmm... given `msg.FromUserName`, how to get its `NickName`?  
(I tried `msg.FromUserName.NickName` but apparently it is not working) 
thx

**Comment by eatmoreapple** [comment]
```
sender, err := msg.Sender()
if err != nil {
	return
}
fmt.Println(sender.NickName)
```
