### ISSUE TITLE
接收到群消息，如何获取到消息来自哪个群？群名称是什么

### ISSUE THREAD

**Issue by styfstr** [eatmoreapple/openwechat#424]
接收到群消息，如何获取到消息来自哪个群？群名称是什么

**Comment by RanX12** [comment]
> 接收到群消息，如何获取到消息来自哪个群？群名称是什么

func(msg *openwechat.Message)

// 是否群组
msg.IsSendByGroup()

user, err := msg.Sender()
user.NickName // 获得群组名

**Comment by styfstr** [comment]
感谢！

**Comment by Yeeyao** [comment]
> > 接收到群消息，如何获取到消息来自哪个群？群名称是什么
> 
> func(msg *openwechat.Message)
> 
> // 是否群组 msg.IsSendByGroup()
> 
> user, err := msg.Sender() user.NickName // 获得群组名

我这边经过测试，如果消息的发送者是当前登录的用户，则这里的 user.NickName  是当前的登录用户名字，不是群名

**Comment by wong8369** [comment]
> > > 接收到群消息，如何获取到消息来自哪个群？群名称是什么
> > 
> > 
> > func(msg *openwechat.Message)
> > // 是否群组 msg.IsSendByGroup()
> > user, err := msg.Sender() user.NickName // 获得群组名
> 
> 我这边经过测试，如果消息的发送者是当前登录的用户，则这里的 user.NickName 是当前的登录用户名字，不是群名 库版本是 v1.4.0

```go
var group *openwechat.User
var err error
if msg.IsSendByGroup() {
	if msg.IsSendBySelf() {
		group, err = msg.Receiver()
	} else {
		group, err = msg.Sender()
	}
}
nickName := group.NickName
```

**Comment by Yeeyao** [comment]
> > > > 接收到群消息，如何获取到消息来自哪个群？群名称是什么
> > > 
> > > 
> > > func(msg *openwechat.Message)
> > > // 是否群组 msg.IsSendByGroup()
> > > user, err := msg.Sender() user.NickName // 获得群组名
> > 
> > 
> > 我这边经过测试，如果消息的发送者是当前登录的用户，则这里的 user.NickName 是当前的登录用户名字，不是群名 库版本是 v1.4.0
> 
> ```go
> var group *openwechat.User
> var err error
> if msg.IsSendByGroup() {
> 	if msg.IsSendBySelf() {
> 		group, err = msg.Receiver()
> 	} else {
> 		group, err = msg.Sender()
> 	}
> }
> nickName := group.NickName
> ```

感谢，这个方法可以获取，不过如果当前登录用户没有将发送消息的群保存到通讯录，就会提示这个

```go
	if msg.IsSendBySelf() {
                 // 这里会提示 err 是：error: no such user found
		group, err = msg.Receiver()
	} else {
		group, err = msg.Sender()
	}
```
