### ISSUE TITLE
[Feature] 群组中成员修改昵称希望可以自动更新

### ISSUE THREAD

**Issue by Yeeyao** [eatmoreapple/openwechat#440]
## 1. 问题描述

1. 登录微信后，在群 A 里用户 a 在群里的昵称是 1，1 发送消息后修改了自己的群里的昵称是 2，然后再发送消息，这边收到的信息里面用户 a 的 displayName 还是 1。预期是 2
2. 相关 bug 单 #433 

## 2. 期望解决方案

1. 如果有群信息变更可以监听然后主动更新本地缓存就最好了
2. 如果 1 条件无法满足，希望能够新增自动定时更新群成员信息功能

**Comment by DOUBLEU9264** [comment]
读取消息发送者时先执行一次 `group.Detail()` 就可以了

**Comment by Yeeyao** [comment]
> 读取消息发送者时先执行一次 `group.Detail()` 就可以了

好的，谢谢
