### ISSUE TITLE
请问如何只获取到保存到通讯录里的群组

### ISSUE THREAD

**Issue by imbentok** [eatmoreapple/openwechat#447]
如题，按文档里来的话只能在登陆后立即调用self.Groups()才能得到通讯录里的群组，如果没在通讯录里的群组有新消息的时，下一次调用self.Groups()获取到的就不仅是通讯录里的群组了。如何解决这个问题呢

**Comment by eatmoreapple** [comment]
登录后立即保存，这时候就是通讯率里面的。
