### ISSUE TITLE
新注册的微信号登录后可以发消息，但是收到消息不触发MessageHandler，只触发一个RetCode:0 Selector:0心跳

### ISSUE THREAD

**Issue by BiHong-Yang** [eatmoreapple/openwechat#453]
同样的代码，我用一个用了很多年的老号登录之后可以正常工作。
但是用一个昨天才注册的新号登录之后，机器人可以往群里发心跳信息，能收到消息，但无法正常触发MessageHandler。
### 测试情况
我在MessageHandler函数内第一行加了一句输出，如果这个函数被触发，咱们立刻输出一条信息。
但我在测试的时候，每向这个账号发一句消息，立刻会输出一个心跳信息，是没有我希望的MessageHandler函数输出。由于这个心跳信息的节律和我发给这个账号消息的节律完全一致，所以暂时可以推断他收到了我的消息。
### 对于网页版微信
我的老账号和这个新账号同样无法登录网页版微信，但是我的老账号是可以正常使用机器人的。

**Comment by BiHong-Yang** [comment]
需要打开支付。。

**Comment by alexQi** [comment]
> 需要打开支付。。

支付已经开通了呀，银行卡也绑定了。但是就是收不到消息
