### ISSUE TITLE
请问Hotlogin功能实现了吗，可以提供一个hotlogin的demo吗

### ISSUE THREAD

**Issue by Sa1Vation** [eatmoreapple/openwechat#47]

**Comment by eatmoreapple** [comment]
```
package main

import (
	"github.com/eatmoreapple/openwechat"
	"log"
)

func main() {
	bot := openwechat.DefaultBot(openwechat.Desktop)
	bot.MessageHandler = func(msg *openwechat.Message) {
		if msg.IsText() && msg.Content == "ping" {
			msg.ReplyText("pong")
		}
	}
	if err := bot.HotLogin(openwechat.NewJsonFileHotReloadStorage("storage.json")); err != nil {
		log.Fatal(err)
	}
	bot.Block()
}
```
单位时间内重启不用再扫码登陆

**Comment by suntong** [comment]
https://github.com/go-openwechat/owc-insight/blob/7bf18fd274f21136963cde3766e63f61c30c2324/main.go#L125-L129

```
	// 创建热存储容器对象
	reloadStorage := openwechat.NewJsonFileHotReloadStorage("storage.json")

	// 执行热登陆
	err = bot.HotLogin(reloadStorage)
```

**Comment by shangdev** [comment]
@eatmoreapple @suntong 热登录后，是否应该在控制台打印一下，haha，`go run main.go` 后一直以为没有登录成功。

**Comment by suntong** [comment]
See my 
https://github.com/go-openwechat/owc-insight/blob/7bf18fd274f21136963cde3766e63f61c30c2324/main.go#L135
@shangdev

**Comment by shangdev** [comment]
@suntong 

热登录失效后（即实际已登出），是否必须删除 storage.json 后，才能继续：go run main.go

**Comment by suntong** [comment]
Yes, @shangdev, as far as I'm aware of, that's what I found that I have to do. 

Maybe we can use this issue to ask @eatmoreapple to fix it so that we don't need to do `rm storage.json` each time.

**Comment by eatmoreapple** [comment]
> @suntong
> 
> 热登录失效后（即实际已登出），是否必须删除 storage.json 后，才能继续：go run main.go



> Yes, @shangdev, as far as I'm aware of, that's what I found that I have to do.
> 
> Maybe we can use this issue to ask @eatmoreapple to fix it so that we don't need to do `rm storage.json` each time.

HotLogin还有个不定长参数，设置为true即可在登录凭证失效后进行扫码登录

**Comment by suntong** [comment]
Let's close this @eatmoreapple
