### ISSUE TITLE
msg.IsLocation()无效,接受位置信息没反应

### ISSUE THREAD

**Issue by keai336** [eatmoreapple/openwechat#476]

**Comment by keai336** [comment]
逻辑好像反了
![image](https://github.com/eatmoreapple/openwechat/assets/147581934/c6df0964-ce11-449c-afe3-aa32cc07f543)
我这么写受到位置信息才有回复.

**Comment by keai336** [comment]
控制台无打印,也没有自动回复.
![image](https://github.com/eatmoreapple/openwechat/assets/147581934/26ebb052-acc2-44c3-ad99-450089233818)

**Comment by keai336** [comment]
好像是这里 的问题,少个 "s''
![image](https://github.com/eatmoreapple/openwechat/assets/147581934/26a1fd05-b514-4142-af13-f169c3233242)
![image](https://github.com/eatmoreapple/openwechat/assets/147581934/b8aaae3f-373f-4cf3-985d-4ac45174986c)

**Comment by eatmoreapple** [comment]
感谢指出Thanks♪(･ω･)ﾉ
