### ISSUE TITLE
not login warn

### ISSUE THREAD

**Issue by suntong** [eatMoreApple/openwechat#5]
Trying to use the main code from readme as is, the program will stop with

`: 301 response missing Location header`

Trying to use 

```go
bot := openwechat.DefaultBot(openwechat.Desktop)
```

the program will stop with

`not login warn`

Presumably coming from

https://github.com/eatMoreApple/openwechat/blob/e751e13afde16351b1e8c1d96a3b00b42d5e928e/items.go#L154

Any solution? 

Thx

PS. On WX side, I did see that, for a moment, it says "Logged in from desktop".

**Comment by eatMoreApple** [comment]
That means your wx could not sign in with `Desktop` mode, please change another wx and try again.

**Comment by eatMoreApple** [comment]
visit [https://wx.qq.com/](https://wx.qq.com/) to confirm if your wx could sign in with

**Comment by suntong** [comment]
I got:

`<error><ret>1203</ret><message>为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>`

openwechat 不是可以突破网页版登录限制吗？

**Comment by eatMoreApple** [comment]
Desktop模式是微信在uos系统上推出的一款微信，其实就是网页版套个壳，它为了能让更多的用户登录，解除了部分用户在网页版的限制，你登录不上可能你的账号没有被开放，不好意思。

**Comment by suntong** [comment]
Oh, that's sad :(. Thanks!

**Comment by eatMoreApple** [comment]
你可以试试最新代码，你这个问题是我之前的一个误解导致的疏漏，现在应该可以登录了。
