### ISSUE TITLE
你的账号无法通过扫码方式登录其他设备。详情请查看微信团队消息。

### ISSUE THREAD

**Issue by iszmxw** [eatmoreapple/openwechat#511]
![image](https://github.com/user-attachments/assets/7282cd1e-3f0e-4736-918d-9376378e842e)

![image](https://github.com/user-attachments/assets/53a4166b-773c-46ff-9905-50b7d5038827)

![image](https://github.com/user-attachments/assets/45f321df-20b7-488b-88ed-ad8101ff516f)

**Comment by Clov614** [comment]
我也遇到过，解除限制就好了。是不是回复时间太短了，被微信检测出来了，加点间隔？

**Comment by iszmxw** [comment]
> 我也遇到过，解除限制就好了。是不是回复时间太短了，被微信检测出来了，加点间隔？

应该是被监控到了，我是21天没有使用了

今天准备来试试，发现被限制扫码了

之前我都没问题的，我感觉是最近一个月才出现的这种情况，因为离我之前最近一次使用是在6月底7月初

@Clov614 楼上又是在什么 **时间节点** 出现的这种情况呢？

**Comment by Clov614** [comment]
> > 我也遇到过，解除限制就好了。是不是回复时间太短了，被微信检测出来了，加点间隔？
> 
> 应该是被监控到了，我是21天没有使用了
> 
> 今天准备来试试，发现被限制扫码了
> 
> 之前我都没问题的，我感觉是最近一个月才出现的这种情况，因为离我之前最近一次使用是在6月底7月初
> 
> @Clov614 楼上又是在什么 **时间节点** 出现的这种情况呢？

总共出现两次，第一次是一段时间未使用后发现被限制了，第二次是开发过程中频繁调试，是小号，注册时间不长

**Comment by iszmxw** [comment]
> > > 我也遇到过，解除限制就好了。是不是回复时间太短了，被微信检测出来了，加点间隔？
> > 
> > 
> > 应该是被监控到了，我是21天没有使用了
> > 今天准备来试试，发现被限制扫码了
> > 之前我都没问题的，我感觉是最近一个月才出现的这种情况，因为离我之前最近一次使用是在6月底7月初
> > @Clov614 楼上又是在什么 **时间节点** 出现的这种情况呢？
> 
> 总共出现两次，第一次是一段时间未使用后发现被限制了，第二次是开发过程中频繁调试，是小号，注册时间不长

我想问，大概发生在什么时间，最近一周还是，2024年的三四月份

**Comment by Clov614** [comment]
> > > > 我也遇到过，解除限制就好了。是不是回复时间太短了，被微信检测出来了，加点间隔？
> > > 
> > > 
> > > 应该是被监控到了，我是21天没有使用了
> > > 今天准备来试试，发现被限制扫码了
> > > 之前我都没问题的，我感觉是最近一个月才出现的这种情况，因为离我之前最近一次使用是在6月底7月初
> > > @Clov614 楼上又是在什么 **时间节点** 出现的这种情况呢？
> > 
> > 
> > 总共出现两次，第一次是一段时间未使用后发现被限制了，第二次是开发过程中频繁调试，是小号，注册时间不长
> 
> 我想问，大概发生在什么时间，最近一周还是，2024年的三四月份

第一次是去年吧，最近这个月发生过一次

**Comment by iszmxw** [comment]
> > > > > 我也遇到过，解除限制就好了。是不是回复时间太短了，被微信检测出来了，加点间隔？
> > > > 
> > > > 
> > > > 应该是被监控到了，我是21天没有使用了
> > > > 今天准备来试试，发现被限制扫码了
> > > > 之前我都没问题的，我感觉是最近一个月才出现的这种情况，因为离我之前最近一次使用是在6月底7月初
> > > > @Clov614 楼上又是在什么 **时间节点** 出现的这种情况呢？
> > > 
> > > 
> > > 总共出现两次，第一次是一段时间未使用后发现被限制了，第二次是开发过程中频繁调试，是小号，注册时间不长
> > 
> > 
> > 我想问，大概发生在什么时间，最近一周还是，2024年的三四月份
> 
> 第一次是去年吧，最近这个月发生过一次

那就奇怪了，难道我的刚好被检测到了

**Comment by Clov614** [comment]
> > > > > > 我也遇到过，解除限制就好了。是不是回复时间太短了，被微信检测出来了，加点间隔？
> > > > > 
> > > > > 
> > > > > 应该是被监控到了，我是21天没有使用了
> > > > > 今天准备来试试，发现被限制扫码了
> > > > > 之前我都没问题的，我感觉是最近一个月才出现的这种情况，因为离我之前最近一次使用是在6月底7月初
> > > > > @Clov614 楼上又是在什么 **时间节点** 出现的这种情况呢？
> > > > 
> > > > 
> > > > 总共出现两次，第一次是一段时间未使用后发现被限制了，第二次是开发过程中频繁调试，是小号，注册时间不长
> > > 
> > > 
> > > 我想问，大概发生在什么时间，最近一周还是，2024年的三四月份
> > 
> > 
> > 第一次是去年吧，最近这个月发生过一次
> 
> 那就奇怪了，难道我的刚好被检测到了

能用则用吧，有个问题，你的消息回复有设置随机间隔吗，其实这个问题在以往的issue中也存在的。解决方案是：装的像一点
参考：[#469](https://github.com/eatmoreapple/openwechat/issues/469)

**Comment by iszmxw** [comment]
> > > > > > > 我也遇到过，解除限制就好了。是不是回复时间太短了，被微信检测出来了，加点间隔？
> > > > > > 
> > > > > > 
> > > > > > 应该是被监控到了，我是21天没有使用了
> > > > > > 今天准备来试试，发现被限制扫码了
> > > > > > 之前我都没问题的，我感觉是最近一个月才出现的这种情况，因为离我之前最近一次使用是在6月底7月初
> > > > > > @Clov614 楼上又是在什么 **时间节点** 出现的这种情况呢？
> > > > > 
> > > > > 
> > > > > 总共出现两次，第一次是一段时间未使用后发现被限制了，第二次是开发过程中频繁调试，是小号，注册时间不长
> > > > 
> > > > 
> > > > 我想问，大概发生在什么时间，最近一周还是，2024年的三四月份
> > > 
> > > 
> > > 第一次是去年吧，最近这个月发生过一次
> > 
> > 
> > 那就奇怪了，难道我的刚好被检测到了
> 
> 能用则用吧，有个问题，你的消息回复有设置随机间隔吗，其实这个问题在以往的issue中也存在的。解决方案是：装的像一点 参考：[#469](https://github.com/eatmoreapple/openwechat/issues/469)

我没有设置过自动回复，也没有把他当机器人用，我就是让他当个消息通知用的，实时发送通知给我的大号
