### ISSUE TITLE
使用扫码登录没问题，使用热登录或免扫码登录去保存登录信息时一直报错，报错位置在编码登录信息时报错

### ISSUE THREAD

**Issue by xionger1-dot** [eatmoreapple/openwechat#523]
断点看编码登录信息两次，第二次时报错
报错信息如下：
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x6 pc=0xe08238]

goroutine 1 [running]:
encoding/json.(*encodeState).marshal.func1()
	D:/anzhuang/GO/src/encoding/json/encode.go:294 +0x10b
panic({0x1163000?, 0x140fd80?})
	D:/anzhuang/GO/src/runtime/panic.go:785 +0x136
encoding/json.appendString[...]({0xc0001f5a9a, 0x1, 0x66}, {0x6, 0xc000258041}, 0x1)
	D:/anzhuang/GO/src/encoding/json/encode.go:971 +0x118
encoding/json.stringEncoder(0xc0003101c0, {0x114d4a0, 0xc00025e920, 0x98}, {0x0, 0x1})
	D:/anzhuang/GO/src/encoding/json/encode.go:590 +0x50e
encoding/json.structEncoder.encode({{{0xc0003cb208, 0xc, 0x10}, 0xc0003888a0, 0xc0003888d0}}, 0xc0003101c0, {0x11a9160, 0xc00025e8f0, 0x99}, {0x0, ...})
	D:/anzhuang/GO/src/encoding/json/encode.go:715 +0x3a3
encoding/json.mapEncoder.encode({0xc000388960}, 0xc0003101c0, {0x115fd60, 0xc000206300, 0x15}, {0x0, 0x1})
	D:/anzhuang/GO/src/encoding/json/encode.go:772 +0xb50
encoding/json.mapEncoder.encode({0xc0003125e0}, 0xc0003101c0, {0x115fdc0, 0xc000121a88, 0x195}, {0x0, 0x1})
	D:/anzhuang/GO/src/encoding/json/encode.go:772 +0xb50
encoding/json.structEncoder.encode({{{0xc0003bcd88, 0x3, 0x4}, 0xc0003889c0, 0xc0003889f0}}, 0xc0003101c0, {0x1190980, 0xc000121a70, 0x199}, {0x0, ...})
	D:/anzhuang/GO/src/encoding/json/encode.go:715 +0x3a3
encoding/json.ptrEncoder.encode({0xc000388a50}, 0xc0003101c0, {0x115b2c0, 0xc000310180, 0x96}, {0x0, 0x1})
	D:/anzhuang/GO/src/encoding/json/encode.go:887 +0x516
encoding/json.structEncoder.encode({{{0xc00039f208, 0x6, 0x8}, 0xc000388b70, 0xc000388ba0}}, 0xc0003101c0, {0x119bde0, 0xc000310180, 0x99}, {0x0, ...})
	D:/anzhuang/GO/src/encoding/json/encode.go:715 +0x3a3
encoding/json.(*encodeState).reflectValue(0xc0003101c0, {0x119bde0, 0xc000310180, 0x99}, {0x0, 0x1})
	D:/anzhuang/GO/src/encoding/json/encode.go:322 +0x7e
encoding/json.(*encodeState).marshal(0xc0003101c0, {0x119bde0, 0xc000310180}, {0x0, 0x1})
	D:/anzhuang/GO/src/encoding/json/encode.go:298 +0x107
encoding/json.(*Encoder).Encode(0xc0002d21e0, {0x119bde0, 0xc000310180})
	D:/anzhuang/GO/src/encoding/json/stream.go:210 +0x1c6
vendor/github.com/eatmoreapple/openwechat.JsonSerializer.Encode({}, {0x2027eb74168, 0xc000116720}, {0x119bde0, 0xc000310180})
	D:/anzhuang/GO/src/vendor/github.com/eatmoreapple/openwechat/serializer.go:19 +0x4b
vendor/github.com/eatmoreapple/openwechat.(*Bot).DumpTo(0xc00017c0e0, {0x2027eb74168, 0xc000116720})
	D:/anzhuang/GO/src/vendor/github.com/eatmoreapple/openwechat/bot.go:321 +0x18a
vendor/github.com/eatmoreapple/openwechat.(*Bot).DumpHotReloadStorage(0xc00017c0e0)
	D:/anzhuang/GO/src/vendor/github.com/eatmoreapple/openwechat/bot.go:306 +0x8e
vendor/github.com/eatmoreapple/openwechat.(*Bot).webInit(0xc00017c0e0)
	D:/anzhuang/GO/src/vendor/github.com/eatmoreapple/openwechat/bot.go:161 +0x41b
vendor/github.com/eatmoreapple/openwechat.(*Bot).loginFromURL(0xc00017c0e0, 0xc0002a4360)
	D:/anzhuang/GO/src/vendor/github.com/eatmoreapple/openwechat/bot.go:137 +0x2dc
vendor/github.com/eatmoreapple/openwechat.(*LoginChecker).CheckLogin(0xc00016da50)
	D:/anzhuang/GO/src/vendor/github.com/eatmoreapple/openwechat/bot_login.go:274 +0x4a5

**Comment by xionger1-dot** [comment]
代码如下：
package main

import (
	"fmt"

	"github.com/eatmoreapple/openwechat"
)

func main() {
	bot := openwechat.DefaultBot(openwechat.Desktop) // 桌面模式

	// 创建热存储容器对象
	reloadStorage := openwechat.NewFileHotReloadStorage("storage.json")
	defer reloadStorage.Close()

	// 注册消息处理函数
	bot.MessageHandler = func(msg *openwechat.Message) {
		if msg.IsText() && msg.Content == "ping" {
			msg.ReplyText("pong")
		}
	}
	// 注册登陆二维码回调
	bot.UUIDCallback = openwechat.PrintlnQrcodeUrl

	// 登陆// 执行面扫码登录
	if err := bot.PushLogin(reloadStorage, openwechat.NewRetryLoginOption()); err != nil {
		fmt.Println(err)
		return
	}

	// 阻塞主goroutine, 直到发生异常或者用户主动退出
	bot.Block()
}

**Comment by eatmoreapple** [comment]
用的go1.23吧

**Comment by xionger1-dot** [comment]
> 用的go1.23吧

是的 是升级后编码的操作不适配了吗

**Comment by eatmoreapple** [comment]
对，暂时没定位到啥问题

**Comment by xionger1-dot** [comment]
> 对，暂时没定位到啥问题

大佬你们用的是哪个版本啊 我换个试试，换成19也有点问题

**Comment by xionger1-dot** [comment]
> 对，暂时没定位到啥问题

非常感谢！，我换成低版本、支持本项目的1.20就可以了
