### ISSUE TITLE
发送较大文件时，出现402 payment required 错误

### ISSUE THREAD

**Issue by ttttyq** [eatmoreapple/openwechat#546]
分片上传文件时，WebWxUploadMediaByChunk方法中 resp, err = c.Do(req)方法报错
![image](https://github.com/user-attachments/assets/1f476f22-084f-4d0b-a208-0cd8a9b557dd)

**Comment by eatmoreapple** [comment]
修复了，支持上传50m以下的文件了

**Comment by ttttyq** [comment]
谢谢🙏
