### ISSUE TITLE
我的微信号在UOS微信(即桌面微信)下可以正常登陆, 但使用openwechat.Desktop却报错

### ISSUE THREAD

**Issue by icepie** [eatMoreApple/openwechat#6]
问题如下
```
访问下面网址扫描二维码登录
https://login.weixin.qq.com/qrcode/4drMSsGf-w==
not login warn
```

**Comment by icepie** [comment]
奇怪的是 https://wechaty.js.org/2021/04/13/wechaty-uos-web/ 这个文章里的demo是可以正常登陆的

**Comment by eatMoreApple** [comment]
不好意思，你这个情况我没法复现，我手头的wx两种模式都可以登录。
看了你的那个链接后发现我有个`target=t`的query没传，现在已经加上，你拉一下最新的试试，看看是不是这个原因。

**Comment by icepie** [comment]
测试了一下 问题依旧....我加你微信了...借号给你试试

**Comment by suntong** [comment]
Why it get closed? 

@icepie does your problem still remain?

**Comment by icepie** [comment]
> Why it get closed?
> 
> @icepie does your problem still remain?

The author fix my problem....but i get a new wrong of sending msg. so about you?

**Comment by suntong** [comment]
Oh, that's why. 

I haven't been able to make mine work yet, neither the two of them work for me :( :(

**Comment by icepie** [comment]
> Oh, that's why.
> 
> I haven't been able to make mine work yet, neither the two of them work for me :( :(

if you meet the same problem about not login warn with `openwechat.Desktop` , maybe you can try it again by git clone the repo (the author close my issue but not with the new commits)

**Comment by suntong** [comment]
Tried just not, still not working see #26, :(
