### ISSUE TITLE
Using self.SendImageToGroup(group, img) and SendFileToGroup(group, file)

### ISSUE THREAD

**Issue by shenly2002** [eatmoreapple/openwechat#65]
Do you have sample code how to use the self.SendImageToGroup(group, img) and self.SendFileToGroup(group, file) please?
I don't know how you forward a file(Image or video) to another group. Thx!

**Comment by eatmoreapple** [comment]
```
package main

import (
    "github.com/eatmoreapple/openwechat"
    "log"
    "os"
)

func main() {
    bot := openwechat.DefaultBot(openwechat.Desktop)
    if err := bot.Login(); err != nil {
        log.Fatal(err)
    }

    self, err := bot.GetCurrentUser()
    if err != nil {
        log.Fatal(err)
    }

    groups, err := self.Groups()

    if err != nil {
        log.Fatal(err)
    }

    if groups == nil {
        file, _ := os.Open("your file path")
        self.SendFileToGroup(groups.First(), file) // or groups.First().SendFile(file)
    }

    bot.Block()
}
```

**Comment by shenly2002** [comment]
if msg.IsPicture() {
				resp, err := msg.GetFile()
				if err != nil {
					return
				}

				defer resp.Body.Close()
				img1, _ := os.Create("test.png")
				defer img1.Close()				
				io.Copy(img1, resp.Body)

				img2, _ := os.Open(img1.Name())
				defer img2.Close()
				group.SendImage(img2)
}

The picture of "test.png" is very vague and not visible. Can I help me with this，Thx.

**Comment by eatmoreapple** [comment]
This problem was solved a few days ago. Please update the latest version and try again.
see `https://github.com/eatmoreapple/openwechat/pull/58/commits/cc05ef03a3c5a889f1a78ca4f75f245d9dd3ab3f`

**Comment by shenly2002** [comment]
> ```
> if msg.IsPicture() {
> 				resp, err := msg.GetFile()
> 				if err != nil {
> 					return
> 				}
> 				defer resp.Body.Close()
> 
> 				img1, _ := os.Create("test.png")
> 				defer img1.Close()				
> 				io.Copy(img1, resp.Body)
> 
> 				img2, _ := os.Open(img1.Name())
> 				defer img2.Close()
> 				group.SendImage(img2)
>                            }
> ```
> 
> Thanks a lot. What about of the video file？

**Comment by eatmoreapple** [comment]
The video would not be compressed. 
I fixed a problem with downloading videos just now.
Update the new version and have a try....
