### ISSUE TITLE
无法获取群组中的用户头像

### ISSUE THREAD

**Issue by wahson-gong** [eatmoreapple/openwechat#69]
`for _,memberItem := range group.MemberList {
				fmt.Println(memberItem.NickName +" : " + memberItem.HeadImgUrl)
				memberItem.SaveAvatar(memberItem.UserName + ".png")
			}`
memberItem.HeadImgUrl 没有数据，保存头像的时候也就会报错了

**Comment by eatmoreapple** [comment]
已修复，感谢指出！

**Comment by wahson-gong** [comment]
> 已修复，感谢指出！

大佬，还发现一个问题，群聊里无法接收到企业微信的用户昵称和回复内容

**Comment by wahson-gong** [comment]
> 已修复，感谢指出！

大佬 测试了新版版，确实可以下载头像了，但是经常会出现下载的头像体积为0字节，这是为什么呢？

**Comment by eatmoreapple** [comment]
> > 已修复，感谢指出！
> 
> 大佬 测试了新版版，确实可以下载头像了，但是经常会出现下载的头像体积为0字节，这是为什么呢？

是的，我也遇到过，暂时不清楚。
但这种用户目前看来都好像是已经废弃了的微信，几乎没有登录过了。

**Comment by eatmoreapple** [comment]
> > 已修复，感谢指出！
> 
> 大佬，还发现一个问题，群聊里无法接收到企业微信的用户昵称和回复内容

我知道有这个问题，但这个目前无法解决。

**Comment by wahson-gong** [comment]
> > > 已修复，感谢指出！
> > 
> > 
> > 大佬，还发现一个问题，群聊里无法接收到企业微信的用户昵称和回复内容
> 
> 我知道有这个问题，但这个目前无法解决。

感谢大佬解惑
