### ISSUE TITLE
你好，关于微信扫码登录问题

### ISSUE THREAD

**Issue by EddieChan1993** [eatMoreApple/openwechat#7]
热登录记录的cookie存在几个小时的过期时间，如果实现登录之后，cookie永不过期

**Comment by eatMoreApple** [comment]
让你的bot一直保持登陆状态，或者在你的cookie即将失效的时候，再次使用热登陆来为cookie续时。

**Comment by EddieChan1993** [comment]
感谢，回复真快

**Comment by EddieChan1993** [comment]
如何让我的bot一直保持登录状态？

**Comment by eatMoreApple** [comment]
不主动退出就行了

**Comment by EddieChan1993** [comment]
好的，我尝试下

**Comment by EddieChan1993** [comment]
我今天尝试了下，发现，一直保持当前服务进程运行，过了没多久bot就失效，alive显示false

**Comment by suntong** [comment]
Oh, that's too bad. Using [wechaty](https://github.com/wechaty/) I had been able to 使用热登陆 on and on for months, until get reset on the server side.

**Comment by EddieChan1993** [comment]
> Oh, that's too bad. Using [wechaty](https://github.com/wechaty/) I had been able to 使用热登陆 on and on for months, until get reset on the server side.

wechaty是需要付费的，没有必要

**Comment by suntong** [comment]
Yeah, that's the exactly the reason I'm trying to make openwechat works for me.
