### ISSUE TITLE
群消息的群组

### ISSUE THREAD

**Issue by suntong** [eatmoreapple/openwechat#71]
Regarding

https://github.com/eatmoreapple/openwechat/blob/9eb84837cbd9207cfa20b0674649102f22b9df29/message.go#L352-L363

@ivy-fish , I'm trying to implement #64, and I'm wondering the `data[0]` part in 

https://github.com/eatmoreapple/openwechat/blob/9eb84837cbd9207cfa20b0674649102f22b9df29/message.go#L357

that's group ID, right? 
and I remember that you said, group ID change every time after fresh login, right?

All in all, if I want to mock a WX  group chat message (from WX server), what would you think the best way to give a group ID that is OK with every/any one? 

thx!!

**Comment by eatmoreapple** [comment]
是的，`data[0] `是群组唯一id`UserName`，至于它生成ID的策略这个我也不知道欸(⊙﹏⊙)

**Comment by suntong** [comment]
OK. Thanks!
