### ISSUE TITLE
第二次热登录 和 HotLogin的不定长参数

### ISSUE THREAD

**Issue by suntong** [eatmoreapple/openwechat#78]
> HotLogin有个不定长参数，设置为true即可在登录凭证失效后进行扫码登录

但是，我不加，或对这个HotLogin的不定长参数设为`false`时，热登录失效后，都会依然要求我进行扫码登录：

![image](https://user-images.githubusercontent.com/422244/130817336-1ed8f6e2-70ba-4654-b064-d5737581b649.png)

My code:

		err := bot.HotLogin(reloadStorage, false)
		_abortOn("Can't restart bot", err, 9)

**Comment by cdle** [comment]
同样的问题

**Comment by suntong** [comment]
See #25
