### ISSUE TITLE
请教msg.ReplyText("pong")后退出

### ISSUE THREAD

**Issue by Zangwill** [eatmoreapple/openwechat#79]
GetMessageErrorHandler 打印 err 显示 `Get "https://webpush.wx2.qq.com/cgi-bin/mmwebwx-bin/synccheck?_=...": net/http: HTTP/1.x transport connection broken: malformed HTTP status code "0"`，链接返回 `window.synccheck={retcode:"1102",selector:"0"}`，网上搜索了下错误，可能是参数或cookie的原因，但是不懂怎么处理

**Comment by eatmoreapple** [comment]
是一开始就有这个错误还是运行了一段时间后出现的。

**Comment by Zangwill** [comment]
发送 ping，可以立即回个 pong，然后大概1秒后出现错误退出。

**Comment by Zangwill** [comment]
另外，经过朴素的实践，发现加个 time.Sleep(1) 后好像可以正常运行了
```
            time.Sleep(1)
            _, err = msg.ReplyText("world")
```

**Comment by Zangwill** [comment]
如图，上面加了个 time.Sleep(1) 的，正常了，下面又把它去掉了，然后只回复了一个又退出了
![](http://ww1.sinaimg.cn/large/005NLHW7ly1guesstt2gcj60u01t042v02.jpg)

**Comment by eatmoreapple** [comment]
ReplyText 返回别的信息会报错吗？

**Comment by Zangwill** [comment]
一样，只要自动回复了，马上就会退出。
<https://paste.ubuntu.com/p/2PVzGkjVbv/>
```     
if msg.IsText() && msg.Content == "你好" {
    msg.ReplyText("世界")
}
```
![](http://ww1.sinaimg.cn/large/005NLHW7ly1gug1sex10zj611y02lte802.jpg)

**Comment by eatmoreapple** [comment]
你好，我运行了你的代码是没有问题的，你看看是不是你网络的问题。

**Comment by Zangwill** [comment]
好的，我再折腾看看

**Comment by Zangwill** [comment]
原因大概想明白了，这个错误应该是 synccheck 请求过于频繁导致的，程序运行到 `msg.ReplyText("pong")` 的时候，有很大概率导致同一个时间戳的两个请求，然后 synccheck请求就会导致 `window.synccheck={retcode:"1102",selector:"0"}` 退出，已提交修改。

**Comment by Zangwill** [comment]
#85 添加 `timeout := time.Duration(30 * time.Second)` 修复问题
