### ISSUE TITLE
定时给文件传输助手发消息可以保活一段时间

### ISSUE THREAD

**Issue by eatmoreapple** [eatmoreapple/openwechat#86]
```
package main

import (
	"fmt"
	"github.com/eatmoreapple/openwechat"
	"log"
	"time"
)

const layout = "2006-01-02 15:04:05"

var duration = time.Minute * 15

func main() {
	bot := openwechat.DefaultBot(openwechat.Desktop)
	bot.GetMessageErrorHandler = openwechat.IgnoreNetworkError(func(err error) {
		fmt.Println(err)
		bot.Logout()
	})
	if err := bot.Login(); err != nil {
		log.Fatal(err)
	}
	self, _ := bot.GetCurrentUser()
	go func() {
		timer := time.NewTimer(duration)
		f, _ := self.FileHelper()
		for bot.Alive() {
			<-timer.C
			f.SendText(time.Now().Format(layout))
			timer.Reset(duration)
		}
	}()
	bot.Block()
}
```

**Comment by chulinx** [comment]
> ```
> package main
> 
> import (
> 	"fmt"
> 	"github.com/eatmoreapple/openwechat"
> 	"log"
> 	"time"
> )
> 
> const layout = "2006-01-02 15:04:05"
> 
> var duration = time.Minute * 15
> 
> func main() {
> 	bot := openwechat.DefaultBot(openwechat.Desktop)
> 	bot.GetMessageErrorHandler = openwechat.IgnoreNetworkError(func(err error) {
> 		fmt.Println(err)
> 		bot.Logout()
> 	})
> 	if err := bot.Login(); err != nil {
> 		log.Fatal(err)
> 	}
> 	self, _ := bot.GetCurrentUser()
> 	go func() {
> 		timer := time.NewTimer(duration)
> 		f, _ := self.FileHelper()
> 		for bot.Alive() {
> 			<-timer.C
> 			f.SendText(time.Now().Format(layout))
> 			timer.Reset(duration)
> 		}
> 	}()
> 	bot.Block()
> }
> ```

定时发送会不会被微信判断为异常？还是在时间范围内取随机值应该比这个靠谱吧

**Comment by eatmoreapple** [comment]
可以的

**Comment by eatmoreapple** [comment]
新版本已连续存活数天，这个方法不需要了
