### ISSUE TITLE
Demo code not working when qq.com is blocked

### ISSUE THREAD

**Issue by suntong** [eatMoreApple/openwechat#9]
```
$ cat /tmp/main.go 
package main

import (
	"fmt"
	"github.com/eatMoreApple/openwechat"
)

func main() {
	bot := openwechat.DefaultBot()

	// 注册消息处理函数
	bot.MessageHandler = func(msg *openwechat.Message) {
		if msg.IsText() {
			fmt.Println("你收到了一条新的文本消息")
		}
	}
	// 注册登陆二维码回调
	bot.UUIDCallback = openwechat.PrintlnQrcodeUrl

	// 登陆
	if err := bot.Login(); err != nil {
		fmt.Println(err)
		return
	}

	// 获取登陆的用户
	self, err := bot.GetCurrentUser()
	if err != nil {
		fmt.Println(err)
		return
	}

	// 获取所有的好友
	friends, err := self.Friends()
	fmt.Println(friends, err)

	// 获取所有的群组
	groups, err := self.Groups()
	fmt.Println(groups, err)

	// 阻塞主goroutine, 知道发生异常或者用户主动退出
	bot.Block()
}

cd /tmp

go build main.go

$ main
Get "https://login.wx.qq.com/jslogin?_=1620437631&appid=wx782c26e4c19acffb&fun=new&lang=zh_CN&redirect_uri=https%3A%2F%2Fwx.qq.com%2Fcgi-bin%2Fmmwebwx-bin%2Fwebwxnewloginpage": EOF

$ go version
go version go1.15.9 linux/amd64

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

It wasn't like this before. What happened? Because this time I'm running under WSL? (was under Linux before)

如何搞定啊大佬？

**Comment by suntong** [comment]
Confirmed that the problem is "***under WSL***"
Redo the above again in a Linux environment works just fine.

**Comment by suntong** [comment]
Confirmed that the problem is actually my company PC is blocking access to qq.com

> does openwechat support using proxy?

Yes. See

- https://www.oreilly.com/library/view/security-with-go/9781788627917/5ea6a02b-3d96-44b1-ad3c-6ab60fcbbe4f.xhtml
- https://golang.org/pkg/net/http/#ProxyFromEnvironment

**Comment by eatMoreApple** [comment]
`bot := openwechat.DefaultBot(openwechat.Desktop)
proxy := func(r *http.Request) (*url.URL, error) {
return url.Parse("raw url")
}
bot.Caller.Client.Transport = &http.Transport{Proxy: proxy}`

关于设置代理，你可以试一下这么做
